### ISSUE TITLE
True Havoc part 1

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#100]
> ### REWORK BOSSES
**Commander Scout**
-Rework ability (remove lunge and new rage)
-Redesign model

**Darkness Hunter**
-Fix skin and update
-Correct attributes weapon
-Redesign rage

**Destiny Destroyer**
-Correct boss info
-Fix yellow skin bug

**Devil Knight Scout**
-Nerf HEALTH 
-New skin
-Remove 2 themes
-Redesign melee attributes

**Syn Luke**
-Fix missing texture of mask

**The Unknown Scout**
-New Skin
-Update info
-Fix steal heavy weapon not work
-Fix iron bomber and smg damage bug
-Fix scorch shot attributes
-Nerf random crits chance
-Buff duration of Dangerous Mode!
-More legit stuff

> ### Suggest Bosses
**Cross Spy**
ความเหอหมอยของคนอ้วนสมัย titan has cum **TRUE**
![se](https://user-images.githubusercontent.com/34367924/84561397-2f53f900-ad76-11ea-9f98-1359999c7116.jpeg)
![cross_spy_edit](https://user-images.githubusercontent.com/34367924/84561370-f3209880-ad75-11ea-9b74-6404f0c9ca86.png)
Abilites:
Super jump and weight down
Passive:
Revive Marker
RAGE:
Festive Amby+Crits+Speed+No knock back+Senty Stun
On Lost Life:
Fog+Outline+Dodge effect

**Demonic Wizard Liafail**
พ่อมดกลายเป็นเด็กส่งของซะงั้น???
![liafailnew_editlow](https://user-images.githubusercontent.com/34367924/84561506-37606880-ad77-11ea-8d49-6e090598df3b.png)
Abilites:
Super jump and weight down
Passive:
Revive Marker
RAGE:
Steal weapon+Fog+Stun+Speed+Outline+Smite+Vaccinator Buffs+No Knock Back
On Lost Life
Change everyone around him to duck+75% Dodge effect+Strength Power up

**Demonic Wizard Luard**
another เด็กส่งของ
![newluard_edit](https://user-images.githubusercontent.com/34367924/84561582-cd948e80-ad77-11ea-9487-027ff9742b9b.png)
Abilites:
Super jump and weight down
Passive:
Revive Marker
RAGE:
Knife+Duck+Stun+Uber+Dodge
On Lost Life:
Black Fog+Smites+Outline+Infinte Jump+Sentry Stun+Reflect+Change Theme+No Knock Back

**DevilBoyZ**
Left4dead like this boss
![newdevilz_edit](https://user-images.githubusercontent.com/34367924/84561784-860f0200-ad79-11ea-8a56-08d90d02108e.png)
Abilites:
Super jump and weight down
Passive:
Revive Marker
RAGE:
Fog+Speed+Steal weapon+Sentry Stun+Defend buff+Outline
On Lost Life:
No knock back+Summon ReaperBoyZ+Stun+Haste

**Future Breaker Machine**
DOOM Eternal is the best
![se1](https://user-images.githubusercontent.com/34367924/84561903-544a6b00-ad7a-11ea-9e18-0f1e5e924932.jpeg)
Poster made by: Neko T!me
Abilites:
Super jump and weight down
Passive:
Revive Marker
RAGE:
Random weapons+Speed Boost+Haste
On Lost Life:
Cosmetic change+Stun+Uber+Fog+Rocket

**Gear Soldier**
legend 
![idklmao](https://user-images.githubusercontent.com/34367924/84561982-05e99c00-ad7b-11ea-98cc-89844c560caf.png)
Abilites:
Super jump and weight down
Passive:
Revive Marker
RAGE:
stun+vaccinator+crit+haste+no knock back+buff+speed
On Lost Life:
Dodge+No knock back+Destory building

**Gentle Millionaire**
gentle mate mate mate my mate nate?
![se2](https://user-images.githubusercontent.com/34367924/84562094-dd15d680-ad7b-11ea-80c4-56dccbc72d50.jpeg)
Abilites:
Super jump,weight down and hook
RAGE:
Stun + Overlay + Invisble
On Lost Life
Uber + Matrix

**GZcross Dimenions Breaker**
Nameless lose this boss inw
![se3](https://user-images.githubusercontent.com/34367924/84562132-4a296c00-ad7c-11ea-85a4-4aafbe74c585.jpeg)
Abilites:
Super jump,Weightdown and dot teleport
Passive:
Revive maker+Precision+Fire Vaccinator
RAGE:
Uber+Stun+Random weapon+No knock back+Crit

**Kaizo**
edgy as fuck
![se4](https://user-images.githubusercontent.com/34367924/84562195-ccb22b80-ad7c-11ea-8d35-d2787f169671.jpg)
Abilites:
Super jump,weight down
Passive:
Revive maker
RAGE:
Drug + 3 point teleport + Ambassador + Uber
On Lost Life
Martix + Stun

**ReaperBoyZ**
lazy make new skin poster 
![se5](https://user-images.githubusercontent.com/34367924/84562250-2f0b2c00-ad7d-11ea-9cc6-ee7b5e546c08.jpeg)
Abilites:
Super jump,weight down,Lunge
Passive:
Revive maker
RAGE:
fog+outline+Timer batsaber+no knock back
On lost life
Change theme+summon koishi+scattergun+stun+uber

**Stealth Master Cross**
ha he is back
![se6](https://user-images.githubusercontent.com/34367924/84562279-84dfd400-ad7d-11ea-9734-3d7273e5fb3d.jpeg)
Abilites:
Super jump,weight down
Passive:
Revive maker
RAGE:
Dark map+outline+invisble+high jump+crit+sentry stun+speed+change everyone look like him
On lost life
Summon 2 shadow+stun

**Topologic Destroyer**
idk to write now ok?
![se7](https://user-images.githubusercontent.com/34367924/84562377-44cd2100-ad7e-11ea-8069-04a963bf403e.jpeg)
Abilites:
Super jump,weight down
RAGE:
Summon dead players+mini crits+Air strike+Sentry stun

**Topologic Knight**
boom
![se8](https://user-images.githubusercontent.com/34367924/84562423-b2794d00-ad7e-11ea-91a8-ce7fc5a03945.jpg)
Abilites:
Super jump,weight down
RAGE:
Berserk + Stun + Explosive + Speed

**Unknown Magician Kurumi**
ez no poster
Abilites:
teleport,weight down,dot rage
RAGE:
Mini-crits+No knock back+Spammer rocket+Sentry Stun+Outline
On lost life:
Stun everyone around you+Uber+Defend buff

Download? google drive 

![cross punisher2](https://user-images.githubusercontent.com/34367924/84562492-1734a780-ad7f-11ea-8223-9daf4953b4c7.jpg)

**Comment by RedTerminal1912** [comment]
cross spy คับ

**Comment by MrTheBank** [comment]
![image](https://user-images.githubusercontent.com/16158569/85247548-4da5ad00-b478-11ea-936c-19720c03fff2.png)
ผิด path ใช่ไหมครับ ของ Glory Luke

**Comment by Reversesniper** [comment]
แก้ download model path ครับ
[fix.zip](https://github.com/MrTheBank/Maxnus-Freak-Fortress-2/files/4811125/fix.zip)

**Comment by MrTheBank** [comment]
Commander Scout
ไม่สามารถ summon ได้ ไม่แน่ใจว่าเป็นเพราะ ff2_salmon คนละ version หรือผิดที่ config

**Comment by Reversesniper** [comment]
ตอนผม test commander scout new ver summon ก็ปกตินะครับ

**Comment by MrTheBank** [comment]
ได้ทำการตรวจสอบ Rework Bosses เรียบร้อยและอัพเข้าเซิฟเวอร์เรียบร้อย

**Comment by MrTheBank** [comment]
Future Breaker Machine บางครั้งเวลาฆ่าคน อาวุธหาย
![image](https://user-images.githubusercontent.com/16158569/85364794-1efa0600-b54e-11ea-9306-aa80abf848cc.png)
GZcross Dimenions Breaker model error
![20200623124218_1](https://user-images.githubusercontent.com/16158569/85365199-0fc78800-b54f-11ea-9587-747552bf2863.jpg)
ReaperBoyZ model error
![20200623124525_1](https://user-images.githubusercontent.com/16158569/85365423-882e4900-b54f-11ea-8ca8-a55cd4a05672.jpg)
Stealth Master Cross
ไฟล์เสียงหาย
![image](https://user-images.githubusercontent.com/16158569/85365997-a6e10f80-b550-11ea-89db-cce7db95733f.png)

**Comment by Reversesniper** [comment]
fix ครับ
[Quack](https://github.com/MrTheBank/Maxnus-Freak-Fortress-2/files/4817745/Quack.zip)

**Comment by MrTheBank** [comment]
ลูกน้องของ Stealth Master Cross model error
![image](https://user-images.githubusercontent.com/16158569/85380516-385b7c00-b567-11ea-9570-622823aaf650.png)

**Comment by Reversesniper** [comment]
fix ครับ
[fixinfix](https://github.com/MrTheBank/Maxnus-Freak-Fortress-2/files/4818215/fixinfix.zip)

**Comment by MrTheBank** [comment]
ได้ทำการตรวจสอบ Suggest Bosses เรียบร้อยและรอการอัพเข้าเซิฟเวอร์
