### ISSUE TITLE
-------FEELS JAPANESE-------

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#101]
> _**PLUGIN ที่จำเป็นต้องใช้ชื่อว่า grip.ff2 อยู่ในโฟลเดอร์ ninjineer นะครับ**_

### **_Ninjineer_**
![image](https://user-images.githubusercontent.com/63923202/84599712-5279c800-ae9e-11ea-8f2a-fa7832e3af4e.png)
NO SUPER JUMP! Try use Grappling Hook
Rage: (Shuriken X5 + Stun)call for medic when the Rage Meter is full
2 lives - You will gain the [Matrix Attack] in 6 and a half second

### **_TANDIMO_**
![image](https://user-images.githubusercontent.com/63923202/84599746-940a7300-ae9e-11ea-98aa-f7efdbadf0d8.png)

> Picture By loftus

he have superjump and dash
Rage: no dmg hellfire + therock + boost speed + swim
signature of him is he always say NEZUKO!

### **_Ota Heavy_**
![otaheavy](https://user-images.githubusercontent.com/63923202/84599798-f19ebf80-ae9e-11ea-8757-9cb3c9d8e921.png)
he have superjump
Rage : uber + dance + pink fog + summon otaku group

### **_Weebshit Scunt_**
![weebshitscunt](https://user-images.githubusercontent.com/63923202/84599840-34609780-ae9f-11ea-96df-451266bea124.png)
He's comback with jojo hat,the best loli pillow and fubuki-chan sign
Rage : explode + summon
Special [use by mouse3] : KAMEKAME HA!!! the light blue dragonball beam!

> ### **_Download : GOOGLE DRIVE_**

ขอบคุณครับ

**Comment by MrTheBank** [comment]
Ota Heavy model error
![20200622091158_1](https://user-images.githubusercontent.com/16158569/85242341-006e0f00-b469-11ea-8862-9b48e7987b47.jpg)
และไฟล์เสียงมีปัญหา ไม่มีเสียงบอสด้วยครับ
![20200622091227_1](https://user-images.githubusercontent.com/16158569/85242361-12e84880-b469-11ea-914a-7efed688f944.jpg)

ที่เหลือผ่านหมดครับ

**Comment by ZELLLLEZ** [comment]
สาเหตุของปัญหา ota heavy
1.materials error : ไม่ได้ให้ไฟล์ vmt ไป และไม่ได้ใส่ตรง download
![image](https://user-images.githubusercontent.com/63923202/85244060-ce12e080-b46d-11ea-88d0-42f86c91f165.png)
2.sound หาย/ไม่ติด : ลำดับเลขไฟล์ผิด
![image](https://user-images.githubusercontent.com/63923202/85244211-3366d180-b46e-11ea-86dd-65add1fa0ea9.png)

ไฟล์ที่ส่งไปรอบนี้จะมีแต่ bzip materials และ materials กับ config แค่นั้นครับ

### **_Download : [fixota.zip](https://github.com/MrTheBank/Maxnus-Freak-Fortress-2/files/4810939/fixota.zip)_**

**Comment by PuShitcake** [comment]
I just combine your Super Minecraft Kid version with ToV version.

![smkreview1](https://user-images.githubusercontent.com/63900170/85246987-90ff1c00-b476-11ea-8a6f-875347cf0553.png)

![smkreview2](https://user-images.githubusercontent.com/63900170/85246995-952b3980-b476-11ea-84c0-12a01cdf2f90.png)

**Download link:**
https://www.mediafire.com/file/byz6dvghj34iyz8/SMK_Combine.zip/file

**Comment by PuShitcake** [comment]
### SammyClassicSonicFan (Remaked Fix)

So many changes.

Boss model:
![sammy-review1](https://user-images.githubusercontent.com/63900170/85359476-8ad57200-b540-11ea-927c-6af1a527be1c.png)

Minion model:
![sammy-review2](https://user-images.githubusercontent.com/63900170/85359488-9163e980-b540-11ea-95d0-f52747b01263.png)

Changes log: 
- Fix abilities, which put double.
- Fix abilities, which write wrong "plugin_name".
- Fix wrong path.
- Add skin "skinfamilies" for both models.
- Better file location.

**Download link:**
https://www.mediafire.com/file/k4rra01yd88m838/Sammy_Classic_Sonic_Fan_fix.zip/file

**Comment by PuShitcake** [comment]
nvm gotta write new issue

**Comment by MrTheBank** [comment]
ได้ทำการตรวจสอบบอสที่เสนอมาเรียบร้อยและรอการอัพเข้าเซิฟเวอร์
