### ISSUE TITLE
Tekken 7 Negan in FF2

### ISSUE THREAD

**Issue by Sun9z** [MrTheBank/Maxnus-Network#102]
### **Lucile is thirsty! She is a vampire bat!**

![myst_scout](https://user-images.githubusercontent.com/53968698/84740555-c966ac00-afd7-11ea-93b6-8eeba6eeed86.png)

**Abilities:**

1. > Superjump: Hold right click and look up
2. > Weigh-down: Hold CTRL and look down
3. > Lose life: LIGHT OUT! (Summon + Black Fog + Outline + Gain Scattergun)
4. > RAGE: Punishment (Crits + No Knockback + Explosion + Defense Buffs + Gain timed The Boston Basher)
5. > Passive: [-] Revive Marker

[Download](https://www.dropbox.com/s/x9kofl5jfwurk67/The%20Mysterious%20Scout.rar?dl=0)
Credits to: Shitcake for helping me and Loftus for old sounds.

**Comment by MrTheBank** [comment]
รบกวนเช็ค config ให้เรียบร้อยก่อนครับ ผมหาไม่เจอละว่าผิดจุดไหน
![image](https://user-images.githubusercontent.com/16158569/85388234-0e5a8780-b570-11ea-9677-7073ea80ecd0.png)

**Comment by MrTheBank** [comment]
ได้ทำการตรวจสอบบอสที่เสนอมาเรียบร้อยและรอการอัพเข้าเซิฟเวอร์
