### ISSUE TITLE
The Famous: Wave #8

### ISSUE THREAD

**Issue by PuShitcake** [MrTheBank/Maxnus-Network#104]
Here, we come my project that I do for 3 days no play TF2.
Let's get to the point

### Pattun Chuen

![pattun r front](https://user-images.githubusercontent.com/63900170/84879055-e6bd7800-b0b4-11ea-95d0-0b58f6a4cf49.jpg)
![pattun r back](https://user-images.githubusercontent.com/63900170/84879066-ea50ff00-b0b4-11ea-92a7-2212285e5b30.jpg)

_A man who said he doesn't like Azur Lane and Artnight but he watch everyday_

What's news?
- Add more sounds (now 66 sounds)
- New model (No-glasses and Touhou symbol reference)
- Buff/Add new rage.
- No revive marker from now on.

His abilities: Super Jump and Weigh-down.
On lose life: Summon his waifu and Matrix.
DOT Rage: No Knockback and Speed Buff (Press RELOAD and drain rage over time)
Main Rage: Uber + No Knockback + Hellfire + Gain Crossbow.

### Le' Esperr BiG
(A.K.A. Big Nga)

![bignga r dou](https://user-images.githubusercontent.com/63900170/84879500-7bc07100-b0b5-11ea-8899-21cef2b87a38.jpg)

_The legend said he still wonder why I call him "Big Nga"._

His abilities: Instant Teleport Point and Weigh-down.
Special ability: Hack player (Press MIDDLE MOUSE to use, cost 30 rage. Need special plugin, already put in file)
On lose life: Matrix + Invisible.
Rage: Fully Stun All + Dodge + Entangles + Damage Spread + Speed Boost. (Damge Spread only deal 100 damage)

**Download link:**
https://www.mediafire.com/file/6r8kai0586qgbk5/Double_Nga_Bosses.zip/file

**Comment by MrTheBank** [comment]
Added Pattun Chuen to server.

**Comment by Reversesniper** [comment]
Shiranuibgm1.mp3
[ff2_hack2.ff](https://github.com/MrTheBank/Maxnus-Network/files/4825665/shiranui.clone.zip)

**Comment by MrTheBank** [comment]
ได้ทำการตรวจสอบ Le' Esperr BiG เรียบร้อยและรอการอัพเข้าเซิฟเวอร์
