### ISSUE TITLE
[FF2] True Havoc part 2

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#106]
> ### SUGGEST BOSSES
**Aqua**
![image](https://user-images.githubusercontent.com/34367924/84987610-aae4ea00-b16a-11ea-9b6c-4fdaa5ba38c3.png)
Abilites:
Summon charge (plugin include in file) and weight down
RAGE:
Make everyone swim in air?+Resistances+Speed boost
On Lost Life:
Stun+Speed+The rock rage
Credits to nameless to make this boss

**Blaze Glaze**
Abilites:
Super jump and weight down
Passive:
he can rocket jump and random crit
RAGE:
Stun everyone and sentry + gain shotgun

**Commander zen**
![image](https://user-images.githubusercontent.com/34367924/84987801-12029e80-b16b-11ea-9c4c-2cab0db69769.png)
Abilites:
Super jump and weight down
RAGE:
Summon players + stun + gain big kill

**Death Machine**
![image](https://user-images.githubusercontent.com/34367924/84987939-4e35ff00-b16b-11ea-9181-dae77a2dc53c.png)
Abilites:
Parkour and weightdown
AMS RAGE:
random weapon
dodge
teleport
stun

**Haunted Duck Pyro**
![image](https://user-images.githubusercontent.com/34367924/84988146-aa008800-b16b-11ea-8dc2-07edfd09b77b.png)
Abilites:
Teleport and weightdown
RAGE:
Turn everyone around him to duck and sentry stun

**Greed**
![image](https://user-images.githubusercontent.com/34367924/84988197-c3a1cf80-b16b-11ea-91e8-3b784b516261.png)
Abilites
Super jump and weightdown
Rage
Buffs+Sentry stun+No knock back+overlay+Speed
Credits: meemfromhh creator of this boss

**Kronos Vanity**
![image](https://user-images.githubusercontent.com/34367924/84988547-65c1b780-b16c-11ea-8a45-b50c54e94e3f.png)
Abilites:
Super jump and weightdown
Passive: 
Revive marker+Immune stun buff
AMS RAGE:
Fog and outline
Crits + Speed + Freeze + Uber
Crits + Strength + No knock back + Uber + Freeze
Random weapons

**Old Nick**
![image](https://user-images.githubusercontent.com/34367924/84988906-fdbfa100-b16c-11ea-9db8-ab4ea9f792e5.png)
Abilites:
Super jump and weightdown
RAGE:
No knock back + speed+ gift rain

**Reimu Hakurei**
Abilites
Super jump and weightdown
RAGE:
Summon clones+Random teleport+Crit+No knock back
On lost life
Martix+Speed

**Shiranui**
![secret 1_2](https://user-images.githubusercontent.com/34367924/84989557-0f557880-b16e-11ea-859d-d063560441cd.jpg)
Abilites
Teleport,Weightdown,Player hack (plugin include),Hijack sentry(plugin include)
Passive: 
Reive marker
RAGE:
Shock everyone around him+Gain Diamond back+Sentry Stun+Speed

**Sky Knight YIP**
ขี้เกียจหาภาพ
Abilites
Super jump and weightdown
RAGE:
Mini-crits+Stun+No knock back+Speed
On lost life
Cosmetic change+Melee change

**Soldine**
![image](https://user-images.githubusercontent.com/34367924/84990326-2d6fa880-b16f-11ea-8907-8d19f2a4efb3.png)
Abilites
Super jump and weightdown
RAGE:
no knock back + random rocket type
Note: ff2_ragesound include in file

**Specter**
![specter_new](https://user-images.githubusercontent.com/34367924/84990447-57c16600-b16f-11ea-86f2-08c05f4162e2.png)
Abilites
Super jump and weightdown
RAGE:
Swap team player that around him+Freeze+Uber

**Swag Spy**
![image](https://user-images.githubusercontent.com/34367924/84990912-05347980-b170-11ea-922d-b896983b8159.png)
Abilites
Super jump and weightdown
RAGE:
Sentry stun+everyone taunt

**The Mask**
![image](https://user-images.githubusercontent.com/34367924/84992485-26966500-b172-11ea-910a-6b66e3556a42.png)
Abilites:
Super jump and weightdown
RAGE:
Random teleport+Drunk+Random weapon+Sentry stun

**Voltage Marshal Claret**
Abilites:
Super jump and weightdown
RAGE:
Reammo trap gun+Orb+Chain lighting

**Zanki**
![zankiedit](https://user-images.githubusercontent.com/34367924/84992895-ba683100-b172-11ea-8f07-cc66eb3d5c38.jpg)
Abilites:
Super jump and weightdown
Passive:
Revive marker
RAGE:
Explosion+Freeze everyone around him+Instant kill everyone around him+Destroy all building+Hell bomb rain

**Zeitwelg or กาว 1000% (thai name)**
![image](https://user-images.githubusercontent.com/34367924/84993242-39f60000-b173-11ea-9bd3-8323a01484c0.png)
Abilites
Super jump,Weightdown,Dot melee
Passive: 
Revive marker
AMS RAGE:
Dodge+No knock back+shield+Defend buff+Freeze players
Crits+Strength+No knock back + Dodge + Defend buff+Freeze players
On lost life
Martix+Uber+de&des building

**download** g00gle DRIVETHO

![eiei](https://user-images.githubusercontent.com/34367924/84993651-c43e6400-b173-11ea-9a1f-f05988bf2554.png)

**Comment by MrTheBank** [comment]
บอสทุกตัวถูกตรวจสอบแล้วครับ ไม่มีปัญหาเรื่อง Model หรือ Missing Texture, Sounds แต่
Specter ใช้ Rage แล้วจบด่านเลย?

**Comment by Reversesniper** [comment]
rage ของ specter เป็นการเปลี่ยนทีมแดงทั้งหมดที่อยู่ใน range ของ rage เป็นทีมฟ้าชั่วคราวครับ
