### ISSUE TITLE
[FF2] Loli rabbit girl

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#108]
### **_Laffey_**
![image](https://user-images.githubusercontent.com/63923202/85231295-199e9d80-b420-11ea-8f0b-7fe47dcac39e.png)
ability : Superjump , weighdown
rage : AMS -gain buff -give rocket

### **_download : https://mega.nz/file/wE9VELoR#jTv3kOMaxg1L-9BNOyH28K_3wMdeznciP5YCNDyReQE_**

**Comment by MrTheBank** [comment]
![image](https://user-images.githubusercontent.com/16158569/85680136-370b8a00-b6f4-11ea-95ef-d8e7591b07c7.png)
ไฟล์เสียงหายไป 1 ครับ
เพลง theme2 เหมือนจะมีปัญหาครับ (ลองลบและโหลดใหม่ใน client แล้ว)
![image](https://user-images.githubusercontent.com/16158569/85680299-5e625700-b6f4-11ea-9085-ad470aa23421.png)

ส่วน ability และ model ปกติดีครับ

**Comment by ZELLLLEZ** [comment]
แก้ครับ (.mp3 .bz2 .cfg)
[fixlaffey.zip](https://github.com/MrTheBank/Maxnus-Network/files/4830060/fixlaffey.zip)

**Comment by MrTheBank** [comment]
theme2 ไฟล์ไม่โหลดเข้า client และผมก็ได้ตรวจสอบแล้วว่ามีไฟล์ theme2fix.mp3 ทั้งเซิฟเวอร์และ fastdl

**Comment by ZELLLLEZ** [comment]
รอบนี้ผมลดเหลือเพลงเดียว
ไฟล์รอบนี้ผม export เพลงจาก audacity อีกที
และเปลี่ยนชื่อไฟล์อีกรอบ คาดว่าน่าจะไม่มีปัญหาแล้วครับ
[fixinfix.zip](https://github.com/MrTheBank/Maxnus-Network/files/4835843/fixinfix.zip)

**Comment by MrTheBank** [comment]
รอการอัพเข้าเซิฟเวอร์
