### ISSUE TITLE
[FF2] Add Bosses #God,Meme

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#109]
### Add bosses

1.AMD Gentle lord

Model
![image](https://user-images.githubusercontent.com/51502238/85328380-d9601d80-b4fa-11ea-8bc0-969c3f70e398.png)

Dot Model
![image](https://user-images.githubusercontent.com/51502238/85328496-04e30800-b4fb-11ea-952a-95f294dbc5f0.png)

Rage Damage 3450
health formula (((640+n)*n)^1.04)
Live 1

**Super Jump - Alt-Fire and Look up**
**Weigh-down: in midair, look down and crouch**

### His Abilities
**Special DOT**
> Press M3 , special attack (Change Model and Gain Buff)
**AMS Rage**
> Rage Speed Buff cost 0
> Rage Stun cost 15
> Rage Dance cost 45
> Rage Nightmare cost  50
> Rage Random weapons cost 75
> Rage switch team cost 100
**Passives**
> Revive Maker

2.Nuclear Soldier

Model frist life
![image](https://user-images.githubusercontent.com/51502238/85329224-4c1dc880-b4fc-11ea-8ed6-a93621311043.png)

Model Lost life
![image](https://user-images.githubusercontent.com/51502238/85329176-33adae00-b4fc-11ea-9dc0-3430b61cfb44.png)

Rage Damage 10000 (You can use Rage 1 only time or 2)
health formula (((400+n)*n)^1.02)/2
Live 2

**Super Jump - Alt-Fire and Look up**
**Weigh-down: in midair, look down and crouch**

### His Abilities
**Rage**
> Gain Super Weapon + Defense Buff + Stun + Stun Sentry + Green Fog + Outline
**Lostlife**
> Change Model + Random Teleport + Uber + Quick Fix all time
**Passives**
> Revive Maker

3.True Thai Announcer

Model
![image](https://user-images.githubusercontent.com/51502238/85329450-be8ea880-b4fc-11ea-8a33-3cea8231644f.png)

![image](https://user-images.githubusercontent.com/51502238/85329466-c77f7a00-b4fc-11ea-8051-cc4c062e37e9.png)

Rage Damage 3800
health formula (((690+n)*n)^1.04)
Live 1

**Super Jump - Alt-Fire and Look up**
**Weigh-down: in midair, look down and crouch**

### His Abilities
**Rage**
> Steal weapon + Gain Buff + Random place Enemies + Outline + Vaccinator

4.IJN Akashi
![image](https://user-images.githubusercontent.com/51502238/85329770-58eeec00-b4fd-11ea-8793-7a33362fa5b6.png)

Rage Damage 3800
health formula (((650+n)*n)^1.04)
Live 1

**Super Jump - Alt-Fire and Look up**
**Weigh-down: in midair, look down and crouch**

### Her Abilities
**AMS Rage**
> Stole weapon (Primary,Secondary,Melee,Building)
> Stealing Next Weapon
> Gain Heath Back

### Remake Boss
1.Hentai Woody Add new sound
2.Japanese style spy and Japanese Winter Sniper Lastest Update model and sound
Model JSS
![image](https://user-images.githubusercontent.com/51502238/85330235-2abddc00-b4fe-11ea-86a2-2172b4ec05be.png)

Model JWS
![image](https://user-images.githubusercontent.com/51502238/85330279-47f2aa80-b4fe-11ea-89a2-d1e3569f2393.png)

3.Ricardo (P.โต) Nerf rage and Add Theme king of the jungle

### Nerf and Buff
1.Amatsu-Mikaboshi Nerf Hp and Update Path nightmare model rage
2.Cataclysm Slaughter Nerf Melee weapon life 2 and sommon Amatsu-Mikaboshi
3.Not Kenzo Nerf Hp and matrix
4.Monika Nerf rage
5.Edgelord Ultima Nerf  Hp
6.MLG Demoman Nerf Range Explosion
7.Super War Machine Buff  Abilitys
8.Biohazard Number 15 Nerf hp
9.Megumin Nerf Hp and rage dmg
10.Fix Outlaw sniper DUO add tag Block

================================================================

Thank you Download link in Google Drive

![พี่โตอยากจ้องคุณ](https://user-images.githubusercontent.com/51502238/85331152-cef45280-b4ff-11ea-947e-54ba841b3977.jpg)

**Comment by RedTerminal1912** [comment]
ชื่อ file ชื่อ Add boss Neko
![image](https://user-images.githubusercontent.com/51502238/85331303-15e24800-b500-11ea-9070-934dd35fd580.png)

**Comment by MrTheBank** [comment]
ได้ทำการตรวจสอบ Remake Boss กับ Nerf and Buff และได้อัพเข้าเซิฟเวอร์เรียบร้อย

**Comment by MrTheBank** [comment]
ได้ตรวจสอบบอสตัวใหม่ 4 ตัวเรียบร้อย และรอการอัพเข้าเซิฟเวอร์

**Comment by RedTerminal1912** [comment]
Jss **(Japanese style spy)** กับ Jws **(Japanese Winter Sniper)** solo ยังเป็น cfg เก่าเลยครับ แอด ยังไงก็ช่วย update cfg นะครับ
ถ้า update แล้วก็ ขอขอบคุณแอดไว้ล่วงหน้าเลยละกัน

**Comment by MrTheBank** [comment]
แก้ไขเรียบร้อย
