### ISSUE TITLE
จาก kaito boss greed and swag spy update

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#11]
Greed
-Buff rage damage from def(1900) to 3100
-nerf hp from 700 to 650
-buff max speed from def(340) to 360
-nerf damage bug abit
-add killstreak and sheen
-change brave jump to dynamic jump
-change normal weightdown to otokiru weightdown
-add model .phy in download

Swag spy
-Buff rage damage from def(1900) to 3300
-nerf hp from 760 to 660
-buff max speed from def(340) to 360
-add killstreak and sheen
-nerf bug damage on knife
-change brave jump to dynamic jump
-change normal weightdown to otokiru weightdown
-fix thriller not work
-fix jump sound and rage not correct slot
-add model .phy download

Download link
https://www.dropbox.com/s/00nzot784g9obye/Greed%20and%20swag%20update.zip?dl=0

**Comment by MrTheBank** [comment]
ถูก **แก้ไข** เรียบร้อย
