### ISSUE TITLE
Double Rage Kids Fix

### ISSUE THREAD

**Issue by PuShitcake** [MrTheBank/Maxnus-Network#110]
### Super Minecraft Kid (Remaked Fix)

I just combine your Super Minecraft Kid version with ToV version.

![smkreview1](https://user-images.githubusercontent.com/63900170/85246987-90ff1c00-b476-11ea-8a6f-875347cf0553.png)

![smkreview2](https://user-images.githubusercontent.com/63900170/85246995-952b3980-b476-11ea-84c0-12a01cdf2f90.png)

Changes log: 
- Add uber skin.
- Fix "skinfamilies".
- Change abilities to ToV version.
- Use old theme. (There's still your new theme)
- Better file location.

Notice: I don't touch DOT ability.

**Download link:**
https://www.mediafire.com/file/byz6dvghj34iyz8/SMK_Combine.zip/file

### SammyClassicSonicFan (Remaked Fix)

So many changes.

Boss model:
![sammy-review1](https://user-images.githubusercontent.com/63900170/85359476-8ad57200-b540-11ea-927c-6af1a527be1c.png)

Minion model:
![sammy-review2](https://user-images.githubusercontent.com/63900170/85359488-9163e980-b540-11ea-95d0-f52747b01263.png)

Changes log: 
- Fix abilities, which put double.
- Fix abilities, which wrote wrong "plugin_name".
- Fix abilities, which forgot wrong "plugin_name".
- Fix wrong path.
- Add skin "skinfamilies" for both models.
- Only 1 skin. (Block voo-doo soul)
- Better file location.

**Download link:**
https://www.mediafire.com/file/k4rra01yd88m838/Sammy_Classic_Sonic_Fan_fix.zip/file

**Comment by MrTheBank** [comment]
ได้ทำการตรวจสอบบอสที่เสนอมาเรียบร้อยและรอการอัพเข้าเซิฟเวอร์
