### ISSUE TITLE
BUFF PACK 5 BOSSES

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#111]
> Beatrice

-fix lose life freeze
-Spell rage cost from 30 to 0
-uber time from 7 to 10 sec
-limit revive to 2
-stun from 5 to 7 sec
-buff dmg melee

> dark realm erandicator

-limit revive to 3
-fix chain lightning
-buff bleeding from 5 to 100 sec
-buff health formula (((650+n)*n)^1.02)/3 to (((670+n)*n)^1.02)/3

> Sewer medic

-buff gun to 1 hit kill
-buff rage condition
=reflect
=50% resistance to all incoming damage
=critsboost
=double firing rate, reload rate, clip size, and max ammo
=all vac uber
=change swim condition
=player got jarate
-buff health
-buff speed
-decrease bomb time

- Only cfg : [buffpack5.zip](https://github.com/MrTheBank/Maxnus-Network/files/4820970/buffpack5.zip)

**Comment by PuShitcake** [comment]
Done, now close your issue.
