### ISSUE TITLE
[FF2]buff my boss in pack 6

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#114]
> Ninjineer

- buff speed
- buff health
- nerf ragedmg
- buff ragedistance
- buff melee
- fix matrix
- buff pull force ability

> Ota heavy

- buff ragedmg
- buff minion
- fix thriller
- nerf rage distance

[buff pack 6.zip](https://github.com/MrTheBank/Maxnus-Network/files/4837709/buff.pack.6.zip)

**Comment by PuShitcake** [comment]
updated.
