### ISSUE TITLE
[FF2] แม่งโคตร weeb เลยวะไอ้ชาย

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#115]
**Bad Doktah**
(Missing picture)
Class: Medic and Sniper
he have 3 lifes
Rage: Crit+Sentry Stun
Lost life: Stun+Uber+Mini-Crits

**Enterprise** obviously cursed
![profile2](https://user-images.githubusercontent.com/34367924/85929785-b316f500-b8e1-11ea-90b0-c76f48984710.jpg)
Class: Sniper
Rage: air raid + Random type weapons + defend buff

**Epic Scout** 
![image](https://user-images.githubusercontent.com/34367924/85929801-dfcb0c80-b8e1-11ea-9743-0e7baf4faffa.png)
Class: Scout
AMS rage
Dodge
Steal weapons
Fake death
Teleport
Random weapons

**Javelin** obviously cursed
![image](https://user-images.githubusercontent.com/34367924/85929810-fe310800-b8e1-11ea-92c9-d68bbe78bc1b.png)
Class: Scout
Rage: Gain rocket + Defend buff

**Sagiri Izumi** NERFED
![image](https://user-images.githubusercontent.com/34367924/85929831-215bb780-b8e2-11ea-8d89-d7476f90592a.png)
Class: Spy
Rage: BFAUDIO + Cosmetic change + Speed Melee + Fast moving

**Sora** 
![image](https://user-images.githubusercontent.com/34367924/85929856-418b7680-b8e2-11ea-9c2d-8ff0adacf59b.png)
Class: Sniper
AMS rage: 
-Extraordinary Specs(100 rage): Gains Crits, 75% chances of dodging attacks, Knockback Resistance, Speed Boost, and Agility Powerup for 10 seconds.
-Delta Field(Sham's Support)(50 rage): Slows down nearby enemies for 5 seconds.
-Shield(40 rage): Gains Defense Buff and Resistance Powerup for 10 seconds.
-Shield Counter(75 rage): Gains all the vaccinator resistance effects and Reflect Powerup for 8 seconds.

**Suguri**
![image](https://user-images.githubusercontent.com/34367924/85929871-5ff17200-b8e2-11ea-9ed1-91aebb040dae.png)
Class: Sniper
-Accelerator(100 rage): Gains Infinite Jump, Minicrit, Defense Buff, Knockback Resistance, and Strength Powerup for 10 seconds.
-Binding Chains(Hime's Support)(75 rage): Stops nearby enemies' movements and give them 'Mark for Death' effect for 2.5 seconds.
-Rainbow-Colored Circle(50 rage): Gains 75% chances of dodging attacks and Agility Powerup for 10 seconds.
-Dash(40 rage): Gains 520 hu/s Speed Boost for 10 seconds.
-Quick Restoration(100 rage): Restores 10% of her base health.(This ability has very long delay and cooldown time.)

**DOWNLOAD!?** yeah google drive

![fububruh](https://user-images.githubusercontent.com/34367924/85929913-9f1fc300-b8e2-11ea-9582-3241120f808b.png)

**Comment by MrTheBank** [comment]
รอการอัพเข้าเซิฟเวอร์
