### ISSUE TITLE
[FF2] what is this shit

### ISSUE THREAD

**Issue by raykoshima** [MrTheBank/Maxnus-Network#117]
Sinyle
ยังไม่มีรูป
class : scout
weapon : Half-Zatoichi(katana)
rage : Stun Sentry + Faster Speed + Entangle + Knockback Immunity + Marked for death on red team + gain random weapon
have 2 lives
Lost Life Explosion 

download(edit)
https://www.dropbox.com/s/0hwtnzp9y8pk1ks/new_name.rar?dl=0
Have fun.

**Comment by PuShitcake** [comment]
If someone wonder how his model looks like.

![sns_scout_preview](https://user-images.githubusercontent.com/63900170/86528849-274f2b00-bed6-11ea-8108-2253802e527d.png)

**Comment by MrTheBank** [comment]
ตรวจสอบเรียบร้อย และได้แก้ไขตรง path download ที่โหลด outtro ผิดให้แล้วนะครับ รอการอัพเข้าเซิฟเวอร์
