### ISSUE TITLE
จาก Neko T!me pls add Michael Myers,Piss Cakehole and Sammy Classic Sonic Fan

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#12]
Michael Myers
http://www.mediafire.com/file/oo684mh4ljvj9aj/Michael+Myers.rar
His Abilities:
Class: Spy
Weapon: Big Earner
Charge Ability: Point Teleport
Any other special ability: 
-Darken the map for the entire round
-Is much faster, when no one is looking at him, while is slow, when being looked at
-Regenerates Rage over time

Rage:
-Turns half invisible
-Gains a massive speedboost
-Gets Knockback immunity and the sprint condition
-Can kill everyone instantly (even ubered players)

He needs the following subplugins:
My own Subplugin (look at the end of this thread to find it)
FF2 Fog
Drain over Time
SHADoW93's Abilities Pack
Sarysa Mods Plugin number 1 + 8
TF Conditions
Powerlord Abilities
Dynamic Defaults

Piss Cakehole
http://www.mediafire.com/file/4qozc2nc6ppy6ip/P%2Ass+Cakehole+V1.zip
class: sniper
weapon: shahanshah
Ability: superjump
rage: stun+uber long time

Sammy Classic Sonic Fan
https://www.dropbox.com/s/xrybvemaic47p1g/SammyClassic.rar?dl=0
weapon: Bat
Ability: Super Jump + Weighdown
RAGE: Gains Grenade Launcher + Mini Crits + Spawns Sonic The Hedgehog
LIVES: You Have 2 Lives, When You Lose One, You Gain Faster Speed, Faster Melee Swing And Slow Mo (NOT MATRIX ATTACK)

ให้ใครก็ได้เช็คก่อนลง server นะครับ แอด bank

**Comment by MrTheBank** [comment]
**ยังไม่ได้ตรวจสอบ** นะครับเพราะคอมหลักเสีย ตอนนี้เพิ่มเข้าเซิฟเวอร์ก่อน หากมีบัคหรืออะไรก็สร้าง Issue ใหม่ได้
