### ISSUE TITLE
[FF2] HoHo

### ISSUE THREAD

**Issue by Le-Insurgency** [MrTheBank/Maxnus-Network#120]
Commander Hunzo
![Commander_Hunzo_new](https://user-images.githubusercontent.com/57568204/86526663-ffa19800-bec0-11ea-911c-17cc47b13601.png)
class : Soldier 
He have 1 life
Rage ams
stun (cost 25 rage)
Buffs (cosr 35 rage)
summon (cost 85 rage)
Gain Rocket Launcher (cost 60 rage)

Have fun
https://www.dropbox.com/sh/eg31vn5jkhgr5l6/AABGRoGKozzZgiGyAR5Aponra?dl=0

![hoho](https://user-images.githubusercontent.com/57568204/86526838-16e18500-bec3-11ea-9ef7-d93b40541a64.png)

**Comment by MrTheBank** [comment]
![image](https://user-images.githubusercontent.com/16158569/90648839-3a3e7480-e264-11ea-95b8-c5801487d85c.png)

**Comment by PuShitcake** [comment]
@MrTheBank fixed

Download link:
https://www.dropbox.com/s/wpi266yy275xrnp/commander_hunzo.cfg?dl=0

**Comment by MrTheBank** [comment]
![20200820073723_1](https://user-images.githubusercontent.com/16158569/90703463-0b51ee00-e2b8-11ea-87f6-1bed575aa211.jpg)

**Comment by Le-Insurgency** [comment]
แก้ models fastdl error 
I'm so sorry
https://www.dropbox.com/sh/a6md8bfe6sopuhn/AAC60VoVxBA0uxfbZ7aOvND9a?dl=0

**Comment by MrTheBank** [comment]
Ugh, Model still error.

**Comment by ZELLLLEZ** [comment]
@MrTheBank 
- fix the wrong path sounds
- new folder name
- fix the wrong download orders
- nerf hp from 690 to 650
- edit summon ability description

**Download link: https://mega.nz/file/cB8x1BBR#P7Q8qOrvcYntebPKw3HvC8Q5Pobmm1cdQ1PJgdggm6c**
