### ISSUE TITLE
[FF2]more boss

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#121]
### **Female sniper By M76030**
![image](https://user-images.githubusercontent.com/63923202/86795632-f6b6ef00-c097-11ea-8c0b-f8ab005ef2a6.png)

Her Abilities:
Class: Sniper
Charge Ability: Super Jump
Any other special abilities: switches to 1 of 9 different melees every time she kills someone with her melee weapon

Rage:
-Everyone around her starts to bleed
-Uses a visual effect on the enemies
-Gets 1 of 7 random weapons

### **Kermit the Frog By ZELL**
![image](https://user-images.githubusercontent.com/63923202/86795937-45fd1f80-c098-11ea-8168-489f35e9d72a.png)

Abilities:
Class: Sniper
Charge Ability: Super Jump

Rage:
-Everyone around him Drunk
-Get Gun (like meme)

### **Seaman**(i can't remember original who make him)
![image](https://user-images.githubusercontent.com/63923202/86797388-cbcd9a80-c099-11ea-9a53-de836867c2c6.png)

[model & sound same seeman but not same ability]
Abilities:
water Arena
Charge Ability: Charge

Rage:
-explosion
-stun

### **Monoculus By ZELL**
![image](https://user-images.githubusercontent.com/63923202/86797128-81e4b480-c099-11ea-8860-bda9d6fbb922.png)

Abilities:
can swin in air
DOT teleport

Rage:
-haste powerup
-crits buff

### **Tatsumaki By ZELL**
![image](https://user-images.githubusercontent.com/63923202/86797681-29fa7d80-c09a-11ea-94ac-2cc6006e5614.png)

Abilities:
Can glide
Charge Ability: Superjump

Rage:
-Push
-Pull
-Entagle
-Reflection
-Stun
-Quickfix Buff

### **Ultra Instinct Shaggy Rework By JuegosPablo**
![image](https://user-images.githubusercontent.com/63923202/86796529-e5baad80-c098-11ea-818b-b9083bcf55c1.png)

Abilities
Super Jump and Weighdown

Rages AMS:
Minicrits + Strengh Powerup (60% Rage)
Ion-Cannon (60% Rage)
Vaccinator Resistences (75% Rage)
Reflect Damage (40% Rage)
Slow Motion + Dodge (65% Rage)
Speed Boost (55% Rage)
Agility Powerup + Knockback Immunity + Dodge Chance (80% Rage)

Lifes=4 (per lost life Swap model + Gain a timed Auto Fire Melee with low damage + Knockback Immunity + Ubercharge)

Special: With 100% Press Special To Shoot a Laser and Gain Ubercharge (Consumes the rage faster)

### **Thanos By SpookyToad**
![image](https://user-images.githubusercontent.com/63923202/86798072-97a6a980-c09a-11ea-8134-27e6661e63a2.png)

Stats
Class: Soldier
Health Formula: ((960+n)*n)^1.04)
Lives: 1
Ragedamage: 3000
Weapon: Fists

Abilites
!USING AMS
1. Power Stone - Lightning (100%)
2. Time Stone - host_timescale 0.2 plus block of all damage (65%)
3. Tesseract - 5 Teleports (40%)
4. Soul Stone - Summon 2 Chitauri with laser weapon (100%)
5. Dynamic Jump

### **Joseph Stalin and Adolf Hitler [DUO] By SpookyToad**
![image](https://user-images.githubusercontent.com/63923202/86798625-2e736600-c09b-11ea-96d1-d5aae725bfeb.png)

**_JOSEPH STALIN INFO_**
Stats
Class: Medic
Health Formula: ((350+n)*n)^1.04/2
Lives: 2
Weapon: Bottle

Abilites
1. Uber for 9 seconds
2. Stun for 5 seconds
3. Bass Cannon with USSR Theme
How it works?
From sky falling Bass Cannon, which plays USSR theme and in radius 1000 H/U Damages players.
(REQUIRES SARYSAYMOD8 WHICH IS INCLUDED IN ARCHIVE)
PASSIVE
1. Jump
2. Weightdown
3. Drops prop of Vodka upon killing
4. Loosing life giving him minigun with 50 ammo in clip

**_ADOLF HITLER INFO_**
Stats
Class: Medic
Health Formula: "(((350+n)*n)^1.04)"
Lives: 2
Weapon: Disciplinary Action

Abilites
1. Uber for 5 seconds
2. Stun for 5 seconds
3. Stun of Sentry Guns for 3 seconds
4. Flamethrower with 25 ammo in clip
PASSIVE
1. Dynamic Jump
2. Dynamic Weightdown
3. Dissolve of players

### **The Siberian Wizard By MeeMFromHH**
![image](https://user-images.githubusercontent.com/63923202/86799109-c2ddc880-c09b-11ea-9ba3-098fc01c70ce.png)

Class: Heavy
Weapon: Fists
Abilities: Magic Teleport; Fireball; Random Spell; Rage
The Siberian Wizard is, as you can already guess by the name, is a wizard, so most of his abilities consist of magic spells (with the exception of his rage, which I will explain in a moment.)
His movespeed is in between a Soldier and a Demo. He jumps 40% higher than normal and is also able to glide by pressing the Spacebar in midair.
His main method of mobility is a Magic Teleport, which instead of teleporting you to an enemy, shoots a projectile in an arc, and you teleport to where it lands (I know most people know how this works, but I'm explaining to those who don't). Right mouse to charge.
He can also shoot a fireball once he has 15 rage. Just hold down Reload to charge it up and release to shoot. Cooldown of about 10 seconds.
He can also shoot a random magic spell with Middle Mouse, but it costs 50 rage.
His regular rage gives him a Crit Brass Beast for 10 seconds, but his movement speed is heavily reduced during those 10 seconds. In lore, whenever Siberian Wizard gets angry, he pulls out a Brass Beast instead of using a magic spell.
He also has 2 lives. When he loses the first life, his theme changes (purely cosmetic effect), and he gets the Agility powerup for the rest of the round. That doesn't do much to his speed, but his jump height is even further increased. Combined with the already higher jump height he has normally, he gets sort of like a chargeless mini Super Jump. In conjunction with his glide and Magic Teleport, his mobility increases even more.

### **ZelanTheBetrayer , Japanese Style Spy , Reverse Future Cross [TRIO]**
![trio](https://user-images.githubusercontent.com/63923202/86801921-b5760d80-c09e-11ea-9bd7-bc06b50d234d.png)

_**zelan**_ 
he don't have superjump in this trio he have only weightdown
his medigun have high ubercharge rate and he get alot of hp
in trio mode his rage style change to 100% good rtd effects
_**jss**_ 
same like the original but he get huge low hp
_**reverse**_ 
he have only teleport and weightdown
his smg deal abit high damage to players
same as tfoc version about lost life and rage

PLUGIN INCLUDE IN DOWNLOAD

 > **DOWNLOAD : https://mega.nz/file/xZ0zGDgZ**

ปล. Decryption key เดี๋ยวผมส่งส่วนตัว [เนื่องจาก Reverse เขาไม่อยากให้คนอื่นมาโหลดไปดูก่อนเข้าเซิฟจริง]

**Comment by MrTheBank** [comment]
รอการอัพโหลดเข้าเซิฟเวอร์
