### ISSUE TITLE
[FF2] True Chaostic Wave #9

### ISSUE THREAD

**Issue by PuShitcake** [MrTheBank/Maxnus-Network#122]
_Finally, end._

-----------------------------------------------------------------------------------------------

### Shoah

![shoah-spy-mix](https://user-images.githubusercontent.com/63900170/89093219-765b8380-d3e2-11ea-8a52-c87526ac2836.jpg)

![shoah-engi-mix](https://user-images.githubusercontent.com/63900170/89093222-79ef0a80-d3e2-11ea-9300-18b02fdecd8c.jpg)

Changes log:
- Improve some materials.
- Remake/Fix model.
- Remake phrase.
- Nerf rage/lose life.
- Nerf HP.
- Increase background music sound.
- Add new model.
- Remove engineer rig model.
- Remove some abilities.
- Change administrator sounds.
- Change theme/intro/outtro.
- Change weapons attributes.
- Fix phrase.

He has a difficulty level, he can change it on rage and lose life.
Each level will be harder and harder for red team.

Passive: Able to backstab.
Negative: Drop revive marker on kill.
His Abilities: Super Jump & Weigh-down
Lose Life: Black fog + Outline + Uber + Instant Teleports
Rage: Crits + No Knockback + Speed + Chain Lightning + Haste Powerup

(Recommend don't add on pack 7, we already have Bad Doctor.)

-----------------------------------------------------------------------------------------------

## True Server Ruler

![true_ruler_preview](https://user-images.githubusercontent.com/63900170/87493784-bfd47080-c677-11ea-9579-ea0ffe048942.png)

![true_ruler_uberview](https://user-images.githubusercontent.com/63900170/87493788-c367f780-c677-11ea-9c0c-2412f7a43f8a.png)

Changes log:
- Improve some materials.
- Less megabyte lastman background music.
- New ability in Ability Management System.
- Remove 1 ability.
- Add new sounds.
- Change lose life ability.

Passive: Able to backstab.
Negative: Drop revive marker on kill.
His Abilities: Super Jump & Weigh-down
Lose Life: Force Nerco Smash to enemy (Whatever this rage can be survive if you roll RTD before boss lose his life, so he will remove your RTD after Necro Smash effect.)
AMS Rage:
- Sins Spector (Outline)
- Slowing In The Dark (Invisible)
- God's Hand (Entangles)
- Return to ZERO (Sucessfully Resistances + Reflect Powerup)
- Despair Syndrome (Switch enemy team for a short time)
- Perfectly Undefeatable (Self-Heal)
- The True Ruler (Chain Lighting)

-----------------------------------------------------------------------------------------------

### Hidden

![hidden-preview](https://user-images.githubusercontent.com/63900170/87494412-21e1a580-c679-11ea-844b-7131d97abd7c.png)

![hidden-uberview](https://user-images.githubusercontent.com/63900170/87494418-24dc9600-c679-11ea-829b-4003d71d7b73.png)

Changes log:
- New file location.
- New materials.
- Improve all materials.
- Fix all materials.
- Fix newest materials.
- Add new abilities on rage.
- Add new abilities on lose life.
- Change all sounds.
- Change time relay speed.

Passive: Able to backstab, Can't be outline, Can't be repels liquid.
His Abilities: Super Jump & Weigh-down
Lose Life: Uber + Damage Spread (In this boss, my point of this ability isn't kill enemy. It's push them away.) + Change Theme + Gain Conniver's Kunai (Which deals more damage and bleeds, but cannot disguise.)
Rage: Invisible + Outline + Black Fog + Speed Boost + Dodge + Gain Festive Ambassador

-----------------------------------------------------------------------------------------------

### John Dick

![IMG_25620821_183217](https://user-images.githubusercontent.com/63900170/87845300-498e7300-c8f0-11ea-84c3-d4fa51e29fd9.jpg)

Changes log:
- Add change team on start.
- Buff speed 310 > 315.
- Fix model.
- Change from "weapon switch ability" to "menu manager".
- Change all rages.

Passive: Able to random crits.
His Abilities: Charge Condition & Weigh-down
Lose Life: Stun + Outline + Mini-Crits + Defense Buff
AMS Rages:
- Guns. Lots Of Guns. (Random Weapon)
- In An Action Scene. (Dodge)
- Rusty, I Guess. (Crits + Speed Buff + Mark For Death Enemies)
- Shutdown Malfunction (Stun Sentry)
- I’m Thinking I’m Back. (Death Ringer)

The legend of this boss is his sounds.

-----------------------------------------------------------------------------------------------

### Phraxāthity̒

![sunshine_preview](https://user-images.githubusercontent.com/63900170/87868960-8f693b00-c9c5-11ea-8960-b4173aece128.png)

![sunshine_lunatic](https://user-images.githubusercontent.com/63900170/87868963-92642b80-c9c5-11ea-8088-639dc960d273.png)

Changes log:
- Remove "Instant Teleport" on rage.
- Fix all abilities key to playable.
- Fix effect which it double.
- Change rage.
- Change description.
- Fix intro music which wrong bitrates.
- Fix weapon index.
- Fix a problem about crashing server.
- Add new theme.

Passive: Able to backstab and turn enemy to minion on kill instantly.
Negative: Drop revive marker on kill.
His Abilities: Super Jump, Weigh-down, Charge Instant Teleport.
Lose Life: Hell Meteror all time (Deals 3 damage per hit, less meteror fall, normal speed and factor and no special effect.) + Gain Festive Ambassador (Which deals really low damage on bodyshot but 1 hit on headshot.), Disguise Kit and more powerful Kunai (Which add more damage and silent and disguise on kill.) + Change Theme
Rage: Invisible + Speed Boost + Overlay + Building Destruction in 400 raidus

-----------------------------------------------------------------------------------------------

### The Last Wizard Of Century

![lastwizard](https://user-images.githubusercontent.com/63900170/89093462-d94e1a00-d3e4-11ea-8bcf-98e9995f9043.png)

Changes log:
- Fix ability which make server crash.
- Fix .vmt which put wrong path to .vtf.
- Change intro.
- Remove outtro.

Nothing special, but he has many special references with a new ability.
(Plugin is in file.)
Also, I change this boss to use .wav instead of .mp3

His Abilities: Charge Grappling Hook (New postision is work well.), Glide, Weigh-down
Lose Life: Matrix + Invisible + Force Enemies Look
Rage: Stun + White Fog + Outline + Force Enemies Eye To Eye + Steal Skill

-----------------------------------------------------------------------------------------------

### Precasfect

A boss from MaKaValz.

![precasfect](https://user-images.githubusercontent.com/63900170/88993400-0b417c80-d310-11ea-96d8-aefca8d9fc87.png)

Changes log:
- Nerf gun damage.
- Nerf gun firing speed.
- Nerf HP.
- Remove second life.

On start, he has all weapons on his hand they are: Australium Riffle which deals very low damage on bodyshot but 1 hit on headshot, SMG Carbine which deals like not so normal damage but low firing speed than usual, Shahanshah which deals low damage too but have high firing speed.

His Abilitiy: Weigh-down
Rage: Stun + No Knockback + Defense Buff + Reflect Powerup + Outline

-----------------------------------------------------------------------------------------------

### Sans

![sans_preview](https://user-images.githubusercontent.com/63900170/89762863-7adb1700-db1b-11ea-857f-0ef525cff6ca.png)

![sans_rageview](https://user-images.githubusercontent.com/63900170/89762870-7e6e9e00-db1b-11ea-8db2-737a5728811f.png)

Changes log:
- Change file location.
- Change rage.
- Add new abilities.
- Remove unused sounds.
- Fix intro.

He has high jump.
He has overlay on each events (Intro, Kill, Rage)

Abilities: Magic Teleport & Weigh-down
Beams: Press MIDDLE MOUSE to use, drain rage over time and Change Model
Rage: Uber + Switch Enemies' team in 285 raidus + Force Enemies Slow and Stare + Ion Cannon where boss stand + Instant Teleports + Change Model
(Rage suggest like his abilities in game, when he control player.)

-----------------------------------------------------------------------------------------------

### Kirby

![kirby-preview](https://user-images.githubusercontent.com/63900170/90652990-dc605b80-e268-11ea-89b1-0ad1c248c242.png)

Change log:
- Update config.
- Fix ability which make server crash.
- Change weapon visibility to 0.
- Add new attributes to weapon. 

His Abilities: Super Jump & Weigh-down
Suck Player: Bring enemies to near boss (Press MIDDLE MOUSE to use, drain rage over time)
Rage: Steal Skill

(Include plugin, same like The Last Wizard Of Century)
ps. It will be good if you put in different pack with The Last Wizard Of Century

-----------------------------------------------------------------------------------------------

**Download link:**
http://www.mediafire.com/file/daqk7dnv2q1sq4o/Chaostic+Wave+bosses+final_lastest.zip/file

- [x] Shoah
- [x] True Server Ruler
- [x] Hidden
- [x] John Dick
- [x] Phraxāthity̒
- [x] The Last Wizard Of Century
- [x] Precasfect
- [x] Sans
- [x] Kirby

-----------------------------------------------------------------------------------------------

If you ask me why my bosses aren't finish and post on github.
I WANT TO LET EVERYONE KNOW BECAUSE LAST TIME MY PROJECT GOT STEAL, IM BIG SAD. XDDDDDD

**Comment by PuShitcake** [comment]
[UPDATE 4]
Changes log:
- Bumped John Dick. 
- Updated download link.

**Comment by PuShitcake** [comment]
[UPDATE 7]
Changes log:
- Bumped Phraxāthity̒
- Added John Dick's replace sounds and full rage alert.
- Update download link.

**Comment by PuShitcake** [comment]
[Final]
Changes log:
- Bumped The Last Wizard Of Century.
- Fixed John Dick. (Shoot credit to ZELL and Reverse)
- Fixed Phraxāthity̒.
- Fixed Hidden.
- Update download link.

**Comment by PuShitcake** [comment]
[Final 5]
Changes log:
- Bumped Precasfect.
- Bumped Shoah.
- Move Shoah's tread to the top.
- Update download link.

**Comment by PuShitcake** [comment]
[Final 9]
Changes log:
- Bumped Sans.
- Update download link.

**Comment by MrTheBank** [comment]
Please upload to Google Drive or somewhere, I cannot download the given link.

**Comment by PuShitcake** [comment]
> Please upload to Google Drive or somewhere, I cannot download the given link.

Changes log:
- Bumped Kirby.
- Update download link.

Here's new download link:
http://www.mediafire.com/file/td3tqp7hanr3nt8/Chaostic+Wave+bosses+final11.zip/file

**Comment by PuShitcake** [comment]
Big update all bosses change logs and abilities, fixed all bosses.
Download link: http://www.mediafire.com/file/daqk7dnv2q1sq4o/Chaostic+Wave+bosses+final_lastest.zip/file
