### ISSUE TITLE
[FF2] Made is Quick And Be the Destroyer Neko And Zell

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#124]
**Suggest Form Neko T!me**

> **1.Agent Pink**

Model
![image](https://user-images.githubusercontent.com/51502238/87812848-051cbc00-c88b-11ea-98bd-98b2de428ec3.png)

Sh*t JOJO reference

Rage Damage 4200
health formula (((620+n)*n)^1.04)/2
Lives 2

Super Jump - Alt-Fire and Look up
Weigh-down: in midair, look down and crouch

**His Abilities**
**Rage**
- Za warudo + stun + Overlay + Hidden Mode
**On lostlife**
- Doge Mode Slow Time+ Sommons + Defense Buff + Pink Fog + Outline

> **2.The Mysterious Mercenary**

Model
![image](https://user-images.githubusercontent.com/51502238/87813492-347ff880-c88c-11ea-95b0-153e69eab6b9.png)

O oh Big 
Machine Devastate rework

Rage Damage 3450
health formula (((640+n)*n)^1.04)

Parkour - Alt-Fire and Look up
Weigh-down: in midair, look down and crouch

**His Abilities**
**AMS Rage**
- Outline
- Defense mode
- Powerful Grenade
- Stealing Weapons classes

> **3.Hentai spy**

Model
![image](https://user-images.githubusercontent.com/51502238/87813876-ef0ffb00-c88c-11ea-85af-6ab0c5aab407.png)

![image](https://user-images.githubusercontent.com/51502238/87813910-ffc07100-c88c-11ea-98bc-9386884f1c3a.png)

Need for Warp plz 
Here | 299058 320116 320229 290846 316407 315443

Rage Damage 3900
health formula (((640+n)*n)^1.03)/2
Lives 2

Super Jump - Alt-Fire and Look up
Weigh-down: in midair, look down and crouch

**His Abilities**
**Rage**
- Hentai Overlay + Drug Effect + Stun sentry
**On lostlife**
- Gain Disguise Kit + stun + sickness effect + Change Theme

> **4.Encounter of Crimson**

Model
![image](https://user-images.githubusercontent.com/51502238/87814244-8d9c5c00-c88d-11ea-881e-875ceec75a42.png)

The Crimson has Arrived

Rage Damage 4000
health formula (((500+n)*n)^1.03)/2
Lives 2

Dot Teleport - Press Reload
Weigh-down: in midair, look down and crouch

**His Abilities**
**Rage**
- Slow Enemies + Uber + Speed Moving + Stun Sentry
**On lostlife**
- Outline
**Passives**
- Crimson Fog + Time Revive Lifes + Immune Eveny Effects + Kill and get heal back

> **5.Cyborg Destroyer**

Model
![image](https://user-images.githubusercontent.com/51502238/87814595-3b0f6f80-c88e-11ea-9e1c-5e29a86e14cf.png)

The Legend of Destroyer

Rage Damage 4000
health formula (((350+n)*n)^1.02)/2
Lives 2

Super Jump - Alt-Fire and Look up
Weigh-down: in midair, look down and crouch

**His Abilities**
**Rage**
- Teleport + Explosive + Stun and Sentry too + Vaccinator + Gain Crits and Quick Fix mode
**On lostlife**
- Aimbot + Matrix + Change theme
**Passives**
- Revive Maker for red team

Download

[Here](https://www.dropbox.com/s/kf9rh1mzt2ah9iv/the%20end%20new.rar?dl=0)

---------------------------------------------------------------------------------------------------------------------------------------------

Thank you... 

---------------------------------------------------------------------------------------------------------------------------------------------

**Comment by RedTerminal1912** [comment]
Update Model Hentai spy (Fix lod model)

**Comment by ZELLLLEZ** [comment]
**Update : Remove all my boss from this issue**
