### ISSUE TITLE
[FF2] neft not kenzo

### ISSUE THREAD

**Issue by raykoshima** [MrTheBank/Maxnus-Network#128]
changelog
neft hp + lostlife matrix
new sound
here this link
https://www.dropbox.com/s/yqznfmk4u7jpyl6/kenzooooooookuyo.rar?dl=0
pai la
pu nom yan นมยานนนน

**Comment by RedTerminal1912** [comment]
แก้ Fastdl ให้ Not Kenzo 
more nerf stun 4 to 3.5

[Download File](https://www.dropbox.com/s/m3rvrr8sytrlbx0/fix%20fastdl%20not%20kenzo.rar?dl=0)

**Comment by PuShitcake** [comment]
Updated to server, delete old file and add new one.
