### ISSUE TITLE
[FF2] fix da da pu toxic

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#129]
Commander zen
-nerf hp

duck pyro
-correct weapon attributes

syn luke
-fix mask download

Havoc
-fix download intromusic

Inwtrue
-fix overlay

Javalin and enty
-change super jump sound to .wav

Orbital strike
-Update config

Perfectshot
-Re model and materials download (change file name )

Reimu 
-Re ability place

Topolgoic destroyer
-correct weapon

Topologic knights
-NERF

DOWNLOAD!?
gooooogleDRIVE

**Comment by PuShitcake** [comment]
sorry for late close, i already put to server right now.
