### ISSUE TITLE
จาก Neko T!me : Fix Michael_myers

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#13]
Fix Michael_myers
เปลี่ยนให้จาก backstab ไม่ได้ 
Fix เป็น backstabbed: Jarate attacker
ที่ส่งเป็น cfg flie
https://www.dropbox.com/s/044q7l5uwpslhsc/michael_myers_fix.rar?dl=0

**Comment by MrTheBank** [comment]
ถูกเพิ่ม **เรียบร้อย**
