### ISSUE TITLE
[FF2]Map Suggestion[include bz2]

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#132]
> **Vsh_EvilRefuge** water? parkour?

![image](https://user-images.githubusercontent.com/63923202/91302332-85aad280-e7d0-11ea-9649-704cff93b5da.png)

> **vsh_foreststation** train? yes

![image](https://user-images.githubusercontent.com/63923202/91302421-af63f980-e7d0-11ea-8dcc-7e1223379138.png)

> **vsh_kaiju_v2** woah we are 100 feet monster now!

![image](https://user-images.githubusercontent.com/63923202/91302475-c4408d00-e7d0-11ea-9552-6a2745574189.png)

> **vsh_ram_shacked_final** old and fun!

![image](https://user-images.githubusercontent.com/63923202/91302879-56e12c00-e7d1-11ea-8b77-4f866230aa17.png)

>**vsh_stargate_v3** portal? woah!

![image](https://user-images.githubusercontent.com/63923202/91302951-724c3700-e7d1-11ea-8dd4-9377f1e3e607.png)

>**vsh_towertop_final** it's like "party island" maybe u got meteor or waterflood

![image](https://user-images.githubusercontent.com/63923202/91303937-e89d6900-e7d2-11ea-91c7-779f5f3d7309.png)

>**vsh_military_area_tfoc** pro version
![image](https://user-images.githubusercontent.com/63923202/91304008-0a96eb80-e7d3-11ea-9862-764908e18704.png)

### **_DOWNLOAD : https://mega.nz/file/Rd01TZCa#ZMOgBLd06nGSyDlx81WtdQa4XaXaZtusBo-1mJ6-i8s_**

**Comment by MrTheBank** [comment]
Added to server, now we have 98 maps in FF2.
