### ISSUE TITLE
[FF2]Fix and update plugin

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#135]
Thanos
- fix AMS
- change use rage button from E to M3
- update new otoriku_wc3 to work with AMS [include in file](replace old otoriku_wc3.ff2 with new one)

Zelan&JSS&Reverse
- nerf Reverse hp
- nerf speed Zelan and increase rage dmg

download: https://mega.nz/file/5Yl0kAKR#BIae9pZoGL1T5YK5Mz7FE-hC9WIawwJT84mRBljkHq8

**Comment by PuShitcake** [comment]
uploaded to server
