### ISSUE TITLE
จาก kaito #3 [Super Dimenions War Break Pack]

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#14]
![dks](https://user-images.githubusercontent.com/34367924/61344670-45aeb780-a87c-11e9-9418-55e7450e1308.jpeg)
Credits poster: Neko T!me
Devil Knight Scout 
(replace sky knight yip and devil hunter scout)
Class: Scout
health formula: (((666+n)*n)^1.04)
ragedamage 3200
maxspeed: 360
1 life
ability:
super jump,weightdown,hook press Reload cool down 3s,Weapon switch between sandman and three rune blade
Passive: Drop revive maker on kill red team and always no knock back.
Rage: stun 2s + sentry stun 8 s.+outline 15s+fog 15s +Strength 10s +speed 10s +crit 10s
sub-plugins Hook and blockdrop power ups are include in file
[Download](https://www.dropbox.com/s/cq2qxtnzcyqssgu/Devil%20knight%20scout%206.6.6.zip?dl=0)

![gzcross](https://user-images.githubusercontent.com/34367924/61345332-c8d10d00-a87e-11e9-8f67-0a1e45ceec3f.jpeg)
Credits poster: Neko T!me
GZcross Dimenions Breaker
(Replace GZcross sniper)
Class: Sniper
health formula: (((660+n)*n)^1.04)
rage damage: 3400
maxspeed: 380
1 life
ability:
super jump,weightdown,Dot teleport press Reload cooldown 5s
Passive: Drop revive maker on kill red team. Precision,Fire Vaccinator
Rage: Random weapon 1 in 6 weapons + uber 6s + no knock back 10s + crit 10s + stun 4s
sub-plugins blockdrop power ups isinclude in file
[Download](https://www.dropbox.com/s/gje364gaag5hu6x/GZcross%20dimenions%20breaker%201.1.2.zip?dl=0)

![ninja](https://user-images.githubusercontent.com/34367924/61346480-1d768700-a883-11e9-9656-ef9175e89448.jpeg)
Credits poster: Neko T!me
Ninja Cross soldier
Class: Soldier
health formula: (((650+n)*n)^1.04)/1.5
rage damage: 3050
maxspeed: 390
2 lifes
ability:
super jump,weightdown
Passive: Drop revive maker on kill red team
Rage: Dark map 15 s+outline 15s + invisble 10s +high jump 10s +crit 10s +sentry stun 8.5s +speed 15s
Lost life: Summon 2 clone + 6 ammo of air strike + stun 5s + sentry stun 10s
Sub-plugins need:  ff2_sarysapub2 for block instant kill katana
[Download](https://www.dropbox.com/s/qezz8y3hsljqqbs/Ninja%20cross%20soldier%201.0.6.zip?dl=0)

![unkown](https://user-images.githubusercontent.com/34367924/61347273-7c89cb00-a886-11e9-873b-d50c4ae5fe06.jpeg)
Credits poster: Neko T!me
The Unknown Scout
Class: Scout
health formula: (((640+n)*n)^1.04)
rage damage: 2900
maxspeed: 380
1 life
ability
super jump,weightdown
Passive: Drop revive maker on kill red team
AMS rage:
Stun everything in map cost: 80% rage
Beserk: gain crit 7.5s mann power 7.5s no knock back 5.5s cost: 90% rage
Steal weapon from player Cost: 100% rage
vaccinator effects cost: 50% rage
Dead ringer cost: 0% rage
[Download](https://www.dropbox.com/s/hpot294r6ovaoaq/The%20unknown%20scout%201.1.1.zip?dl=0)

Duo boss coming soon

ถ้าต้องการ ให้ nerf บอกได้นะคับ
รอบนี้มันจะดู โกงๆ หน่อยคับ

**Comment by MrTheBank** [comment]
**Approved**, Added to Pack # 6
