### ISSUE TITLE
[FF2] Apple pie NERRF DADADADADADA

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#142]
**Perfectshot Zetta**
-Update skin
-Rework abilities
-Remove 2 themes
-Btw all red team damage decrease by 15% (all weapons)

**conclusion of Havoc**
-Remove broken content
-Add 1 ammo to diamondback

**Inwtrue**
-Increase rage damage
-Increase revive marker from 1 to 3
-RNG

Download?
somewhere but not here
![error](https://user-images.githubusercontent.com/34367924/99272376-4ed9db00-285a-11eb-9c0f-6861f7e34bb7.gif)

**Comment by PuShitcake** [comment]
Updated.
