### ISSUE TITLE
[FF2]exterminate time ruler

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#144]
**General**
Remove 2 bgms and replace with new one
New outtro music
**Buff**
All red members's melee dmg decrease by 90%
High Jump
No long get full stun
No long get milked
**Nerf**
Increase jump cooldown time
more drain rage per sec (shield mode)
Increase ragedamage require
Nerf speed

**Download**
what is this?

![เอ๋อ](https://user-images.githubusercontent.com/34367924/100521551-154c8c80-31d7-11eb-9eaf-1cb3dde16625.jpg)

**Comment by PuShitcake** [comment]
updated
