### ISSUE TITLE
[FF2]Nerf TRIO

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#147]
Zelan
Speed : 340 > 320
Ragedmg : 3200 > 4000
RTD rage : always good > normal RTD
Player Hook : -10 > -7

Reverse
Speed : 360 > 340
Spell rage cost : 30 > 50 CD : 10 > 20
Hp : (((715+n)*n)^1.04)/1.8 > (((280+n)*n)^1.02)/1.8
Rage move speed : 520 > 450,Duration : 13 > 10
Heffe lost life : no more smite but stun duration increase from 2 > 3
chain lightning dmg : 70 > 50

JSS
Hp : (((350+n)*n)^1.04)/2 > (((200+n)*n)^1.04)/2
Jump cd : 7.5 > 9

DL : https://mega.nz/file/RQFyAJqJ#GIOhqxH5OIywkVRqv3RdJAbvQxEw63bdHe4Gdyq0Opg

note : now boss team can get fire work smite etc. :3

**Comment by PuShitcake** [comment]
updated to server
