### ISSUE TITLE
จาก shitcake buff,fix bosses และ new boss

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#15]
BUFF AND FIX
MrTheBank
Dr.Ben
High leader soldier
Legendary laugher
ninja slayer
ppkueyza
shitcake
pattun chuen

New boss
Ruthless Slaughter
Class: Scout
rage damage 2800
health formula (((599+n)*n)^1.04)/1.95
maxspeed 520
2 lifes
ability : superjump weightdown, slam press middle mouse cost 25% rage
passive:No knock back and drop revive maker on kill
rage: Stun 3s + Uber 10s + Gain 3 Entangles
Lost life: Dodge + Defense buff + Reflect powerup + Mark for death enemy

[Download all stuff](https://www.dropbox.com/s/yij9m9dhpxtc4ic/Shitcake's%20new%20BOSSES.zip?dl=0)

**Comment by MrTheBank** [comment]
Ruthless Slaughter **ผ่าน** ครับ ถูกเพิ่มเข้าเซิฟเวอร์เรียบร้อย และ ส่วนที่เหลือก็ถูกเพิ่มเข้าเรียบร้อย
