### ISSUE TITLE
[FF2] Nerf and Buff for Perfect and balance game!

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#151]
### **Nerf**
> Crimson
- Nerf health formula and set 1 live

>Cyborg Destroyer
- Nerf his speed too fast 520 > 405

>Agent Pink
- Add revive maker for red team 200 seconds limit 8
- Set new Rage damage 4000 > 4200
- Set new HP Formula

----------------------------------------------------------------------------------------------------------------------------------------------

### **Fix and Add**
>Hentai spy
- Set Rage damage 3900 > 4000
- Remove Lostlife theme
- Nerf Super Jump
- Update NH codes
- Update Sound change mp3 to wav
- Add Rage mad milk stun (cum shot)

plugin
Happy to mad (get plugins in Hentai spy file)

Download
[Here](https://drive.google.com/file/d/1hK-UsyXSE-fOvyER2RaEw7gl0BYXMgMu/view?usp=sharing)

----------------------------------------------------------------------------------------------------------------------------------------------

Thank you

![sexy](https://user-images.githubusercontent.com/51502238/102642536-6e815d80-4190-11eb-915f-80a514df8fee.jpg)

**Comment by PuShitcake** [comment]
updated configs and plugin to server
