### ISSUE TITLE
[FF2] Add my oc boss

### ISSUE THREAD

**Issue by Le-Insurgency** [MrTheBank/Maxnus-Network#152]
> Removed Winter Killer Lance and replaced with InsurUltimateChaos

Name - **InsurUltimateChaos**
![leeeee (2)](https://user-images.githubusercontent.com/57568204/102643986-ae494480-4192-11eb-91bf-f1029614cb47.png)

> Our mighty fallen begotten power
**Never surrender**

He Has 2 lives

Passive: Drop revive marker on kill.
His Abilities: Super jump & Weigh-down
Rage: Gain random weapon + stun
Lose Life: Uber + summon minion + fog + ioncannon

Download
[DO IT!](https://www.dropbox.com/sh/m3fkttqjpaepj81/AAADSUFU5wLlodTMn0URgtTWa?dl=0)

![FB_IMG_1596966662350](https://user-images.githubusercontent.com/57568204/102644687-cf5e6500-4193-11eb-8cba-478a5d21cb4e.jpg)

**Comment by Le-Insurgency** [comment]
[Bruh](https://www.dropbox.com/sh/zbmf0br1hbpc1hx/AABiNhRaUqnhAkOfLqwtpLNNa?dl=0)
**fix sound and nerf buff**

> Nerf Rage damage 3200 > 3500 and nerf weapons ammo
> Buff Health formula 700>705

**Comment by PuShitcake** [comment]
updated to server
