### ISSUE TITLE
[FF2]Abyss of Trance

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#154]
> ### **REPLACE BOSS**
**Demonic wizard DUO** (replace luard and liafail solo)
same as the original but come with different theme

> ### **REMASTER BOSS**
**Zetiwelg**
Change to menu ability
Add new theme
New Skin
New sound
New ability
![hlmv_4j4Xbq4MpZ](https://user-images.githubusercontent.com/34367924/102713263-8c1e0680-42f9-11eb-98a9-0c69b71416a9.png)

> ### **NERF BOSS**
**INWTRUE**
Increase rage damage to 7777
Nerf hp formula to 700
Nerf max speed to 390
Increase revive marker limit to 5
Remove theme 2
Nerf uber duration to 5
Nerf dodge and no knock back duration to 7
Increase superjump cooldown to 12s

**Download**
Not here

![image](https://user-images.githubusercontent.com/34367924/102713314-136b7a00-42fa-11eb-8009-5e1d16ed152a.png)

**Comment by PuShitcake** [comment]
updated to server, replace those duo and zeitwelg. before its unplayble boss, i buffed inwtrue's ragedamage to 6,200 instead of 7,777. thanks.
