### ISSUE TITLE
จาก Neko T!me เพิ่ม boss มา 2 ตัว (Black and White murderer) Add in pack 6

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#16]
Black Murderer and White murderer
Classes spies
weapon
(Black : Festive knife | White : Knife)
Abilitys
(Black : Super Jump | White : Teleport || have weight down)
Rage
(Black : Clock + stun and sentry + teleport points 4 + gain ambassador)
(White : Clock + stun and sentry + uber + gain ambassador + outline)

(DUO will Coming soon)
I credits 2 bosses with kaito
this file have 2 files 
Black murderer
https://www.dropbox.com/s/tqycs1ea63d2igs/Black%20Muderer.rar?dl=0
White murderer
https://www.dropbox.com/s/g96wcwvy4t9x7gj/WhiteMurderer.rar?dl=0

**Comment by MrTheBank** [comment]
เพิ่มเข้าบอสแพ็คที่ 6
