### ISSUE TITLE
[FF2]The Legend is back!!

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#161]
### **Remove**

- The Mysterious Mercenary

**### Replace**
Machine Devastate

![image](https://user-images.githubusercontent.com/51502238/103474024-f5117e00-4dd1-11eb-8457-8fe7bbe78b82.png)

1. ragedamage       4200
2. health_formula   (((690+n)*n)^1.03)/3
3. speedmoving     340
4. lives			   3
5. Lunge dash        20 cost rage (Press Reload)
6. Super Jump       Hold Alt-fire and look up
7. Weigh down      Hit midair, look down and crouch.
8. Rage                  Stun + Randoms 6 weapon + No knock back + Stun Sentry + outline + uber
9. Lostlife               Fog + Shield Power up + No knock back
10. Add Revive for red team

[Download](https://drive.google.com/file/d/17wU1RbZ0crlpbWSew_5CHqNkkvUwSR5a/view?usp=sharing)

Thank you

----------------------------------------------------------------------------------------------------------------------------------------------

![เดเดกเ](https://user-images.githubusercontent.com/51502238/103474125-5554ef80-4dd3-11eb-9e1a-4baeabcd2279.PNG)

**Comment by PuShitcake** [comment]
added to server, o oh ay
