### ISSUE TITLE
[FF2] Replace #2

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#162]
### **Remove**

- The Creator มาแทน God of Intergalactic
- Iconoclast มาแทน Holiday Demodrunk 

**### Replace**
1.The Creator

![image](https://user-images.githubusercontent.com/51502238/104195809-a7da7f80-5455-11eb-93ab-7fe44d6b57d1.png)

health_formula              (((620+n)*n)^1.03)/2
speedmoving                360
lives			              2
Super Jump                   Hold Alt-fire and look up
Weigh down                  Hit midair, look down and crouch.

Rage Menu Manager
[1]RED SPOTTED            Outlines Enemies
[2]Instant Kill                  Rage The rock
[3]Classes Random         Change classes all red team
[4]No Pain No Gain        Gain 2 weapons
[5]Low Visibility              Black Overlay
[6]The Imminent Death  Freeze enemies and slay them in 500m

Lostlife                           Stun + Explosion + Destroy Building around map
Add Revive for red team
(ไม่รู้ว่าจะ bug ไหมเพราะ ไม่ได้ผ่านการ test ทดสอบความ balance boss กับ bug)

2.Iconoclast

![image](https://user-images.githubusercontent.com/51502238/104196242-20414080-5456-11eb-8110-c7369237080f.png)

health_formula                (((580+n)*n)^1.04)
speedmoving                  350
Air dash                           Jump and hold Ctrl
Weigh down                   Hit midair, look down and crouch.
Rage                               Berserk + Outline + Explosion + Stun sentry

Thank you

[Download](https://drive.google.com/file/d/14S0EktVTL9GsahHxAvO5NJpO9jPMecuq/view?usp=sharing)

----------------------------------------------------------------------------------------------------------------------------------------------

![นก](https://user-images.githubusercontent.com/51502238/104197977-3fd96880-5458-11eb-959d-ea6d5ac417fe.jpg)

**Comment by PuShitcake** [comment]
replace them to server
แต่นี้ไปขอพักการ replace boss ก่อน เนื่องจากถี่เกินไป และตัวสุดท้ายคือของผมเอง
