### ISSUE TITLE
จาก kaito ReaperBoyZ and Ruthless Slaughter fix and buff

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#17]
ReaperBoyZ
Maxspeed change:
Buff speed: 380 > 390

Weapon change
His pistol: Add death marker on hit
His melee: Add Mini crit become crit and change damage reduce 0.45 to 0.65

Ability change:
Super jump: buff jump intensity multiplier 1.1 > 1.2 , reduce first time use cooldown and buff cooldown time 5.0 > 6.0

Download change:
Add somemissing sound to download list (rage and lost life bgm sound)

Ruthless Slaughter
Hp change:
health formula "(((599+n)*n)^1.04)/1.95" to "(((545+n)*n)^1.04)/1.95"
Rage damage change: 2800 to 2450

[Download](https://www.dropbox.com/s/m907v3yfte6o17u/Reaperboyz%20and%20RS%20buff%20and%20fix.zip?dl=0)

**Comment by MrTheBank** [comment]
ถูกเพิ่มเข้าเซิฟเวอร์เรียบร้อย
