### ISSUE TITLE
Anther one boss Name Intergalactic Maxtinus

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#18]
Class Medic
weapon ubersew
Abilitys super jump
rage (stun + lighting + ailen beem from sky 8)
2 life

https://www.dropbox.com/s/mahere9h375iylh/Intergalactic%20MaxtrinusV2.rar?dl=0

**Comment by MrTheBank** [comment]
**Approved**, Added to Pack # 6
