### ISSUE TITLE
Suggesting my bosses for upcoming Boss Pack 6

### ISSUE THREAD

**Issue by NamelessTheNueProducer** [MrTheBank/Maxnus-Network#19]
1. TOP Idol Nue Houjuu
![top idol nue houjuu listen2](https://user-images.githubusercontent.com/53435085/62052116-d491db80-b24f-11e9-9bde-3dd7cf8c6edd.jpg)
(Poster made by me)

Stats
Class: Spy
Health Formula: (((765+n)*n)^1.02)
Lives: 1
Movement Speed: 400 hu/s ~ 520 hu/s(The less health she has, the faster she goes)
Total damage needed to activate rage: 3460
Weapon: Saxxy(has 50% damage reduction to prevent the high knife damage, and also has 20% faster swing speed and can disguise on backstab)

Abilities
Mobility: Super Jump, Timed Grappling Hook(Press Middle Mouse to use for 5 seconds. It has 2.5 seconds cooldown), Weighdown
Other Abilities:
-Drops revive maker on kill and RED team's medic can revive their teammates. Also the revive maker lasts forever till the round ends.
-All RED team players will get grappling hook till their first death. It can't be used again if they're revived from their medics.
Rage: Stun all sentries for 14 seconds + Goes invisible for 14 seconds + Freeze all players and their movements for 6 seconds + Force all players do the Thriller taunt once + Gains 520 hu/s Speed Boost for 14 seconds + Makes abduction beams around her, but it's 4 times more than her normal version(40 beams).

The hook for players subplugin is included in her download file.

Download
http://www.mediafire.com/file/mudvsn7gc2migii/TOP_Idol_Nue_Houjuu%2528maxnus_ver%2529.zip/file

2. Super Pro Demoman
![super pro demoman](https://user-images.githubusercontent.com/53435085/62057671-08bec980-b25b-11e9-8487-3676d990453c.jpg)
(Poster made by Doctor Lalve, who made Super Pro Demoman video)

Stats
Class: Demoman
Health Formula: (((650+n)*n)^1.04)
Lives: 1
Movement Speed: 340 hu/s
Total damage needed to activate rage: 3000
Weapon: Bottle(Nothing special for his startup melee, but hard to explain all 7 different melees he switches so I won't go deep on that)

Abilities
Mobility: Lunge(Has no damage when hitting an enemy, but destroys buildings instantly, and has 4 seconds of cooldown), Weighdown
Other Abilities: Switches 1 of 7 different melees every time he kills someone. Each melee has different stats that was featured in the video.
Rage: Stun all sentries for 8 seconds + Gets Uber, Haste Powerup and Disciplinary Action Speed Boost(All 8 seconds) + Gets 1 of 3 different grenade launcher for 8 seconds. Each grenade launcher has rapid fire rate and reload speed, but low damage.

Download
http://www.mediafire.com/file/w7hx4zgry7rlxwf/Super_Pro_Demoman.zip/file

3. Hat Kid
![hat kid2](https://user-images.githubusercontent.com/53435085/62057873-63582580-b25b-11e9-9915-3a690396fef8.png)
(Poster from her game, A Hat in Time)

Stats
Class: Scout(3rd person is Sniper because the model is rigged to Sniper's bones)
Health Formula: (((550+n)*n)^1.04)/4
Lives: 4
Movement Speed: 270 hu/s
Total damage needed to activate rage: 2000
Weapon: Freedom Staff(Its weapon name is tf_weapon_club so it doesn't act like a scout's melee, but as a normal melee. Her melee gives her 30% higher jump height and 25% knockback resistance, but has 30% damage reduction.)

Abilities
Mobility: Grappling Hook(Press 6 to use, can be swapped very fast but takes 50% more critical damage while using.), Lunge(Press Alt-Fire to use, has no damage when hitting an enemy and buildings, and has 3 seconds of cooldown), Weighdown
Other Abilities:
-Her size is 0.7 times smaller than the other bosses.
-Mouse3 DOT Ability(Projectile Badge): Gains uber and fires a laser with infinite range after 3 seconds. It can be controlled 360 degree angle and deals around 50 damage per 0.1 second. It needs 100% RAGE to activate and has 90 sec cooldown.
Rage: She has AMS (Ability Management System (Basically you can choose whatever RAGE you wanna activate (Switching by pressing RELOAD)))
-Sprint Hat(30 rage): Gains 520 hu/s Speed Boost for 10 seconds.
-Brewing Hat(40 rage): Gets 3 explosive vials.(Mutated milk in 1st person, but becomes a cannonball projectile with vial model when throwing)
-Ice Hat(50 rage): Stuns nearby players and sentries.(6 seconds for players in small radius, and 8 seconds for sentries in large radius.)
-Time Stop Hat(75 rage): Slows down time while dodging attacks from enemies for 12.5 seconds.
Lifeloss Ability: Gets Hidden Uber for 5 seconds.

Download
http://www.mediafire.com/file/8de436055b22k8z/Hat_Kid.zip/file

**Comment by Reversesniper** [comment]
nice desu.

**Comment by MrTheBank** [comment]
**Approved**, Added to Pack # 6
