### ISSUE TITLE
จาก ❤>{?Mr.Left 4 Death 2?}<❤

### ISSUE THREAD

**Issue by MrTheBank** [MrTheBank/Maxnus-Network#2]
https://forums.alliedmods.net/showthread.php?t=303062

Mr.Left 4 Death 2 Today at 11:34 AM
เอาฮะ
เดียวผมเลือกให้ก่อน
เพราะมันมีตัว op
ผมจะเอาให้พวก กลางๆ
เอา Pessimistic Spy  Orbital Sniper
พวก นี้ กลางๆ สุดละ
เพราะ ที่เหลือ server คงต้อง x10

http://www.mediafire.com/file/tjcxjmy46qp5zde/OrbitalSniper.zip
https://www.mediafire.com/file/eyytjd6axcl0z7a/Pessimist.zip

**Comment by Reversesniper** [comment]
Pessimistic Spy
-now model always blue 
-nerf maxspeed from 400 tp 350
-More info 
-fix knife damage bug
-change teleport to dynamic teleport
-add killstreak and sheen to weapons
-rage stun for 4s
-fix bgm2 and 3 not working
-add download .phy file
-add fastdl file
Download link
https://www.dropbox.com/s/nf0i0tr8vkvim1j/Pessimist%20spy%20fix.zip?dl=0

Orbital Sniper
-now model always blue
-nerf hp formula from 700 to 640
-more info
-change brave jump to dynamic super jump
-fix shooting star dmg bug 
-add killstreak and sheen to weapons
-change big head effect on boss condition to no knock back for 10s
-reduce big head effect time on red from 30s to 15s
-add model .phy download
-add fastdl file
Download link
https://www.dropbox.com/s/vmpxxqxmid0mdk0/Orbital%20sniper%20fix.zip?dl=0

**Comment by MrTheBank** [comment]
Orbital Sniper, Pessimistic Spy **ผ่าน** บอสจะถูกแอดในแพ็ค # 5
