### ISSUE TITLE
From Neko T!me Add Boss Machine Devastate in pack 6

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#21]
Class Sniper
Weapon Crossing Guard
3 lifes
Mobility : Super jump and Weigh-down
20 rage Lunge
30 rage Slam Down
100 Rage Random weapons

https://www.dropbox.com/s/e5u1m1kk9u6tmvz/machine_devastate.rar?dl=0

**Comment by MrTheBank** [comment]
**Approved**, Added to Pack # 6
