### ISSUE TITLE
Buff and Nerf Dimenions pack

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#25]
Ninja Cross Soldier
-Nerf minions hp

GZcross dimenions breaker
-More ragedamage
-Buff hp abit
-Fix vmt not download

Devil Knight Scout
-Buff speed
-His second melee firing rate like scout now

[Download](https://www.dropbox.com/s/2dhg8so3knri8zs/Dimenions%20pack%20buff%20and%20nerf.zip?dl=0)

**Comment by MrTheBank** [comment]
แก้ไขเรียบร้อย
