### ISSUE TITLE
Suggesting more 'normal' bosses to add in pack 6

### ISSUE THREAD

**Issue by NamelessTheNueProducer** [MrTheBank/Maxnus-Network#26]
I'm glad that boss pack 6 is out. But it seemed like there were too many revive maker bosses except 2 bosses. So I'm suggesting these normal bosses so that it won't be always a revive maker boss every round.
Keep in mind that these bosses were originated from others' FF2 Alliedmodders post.

1. Beep Man
![beep man](https://user-images.githubusercontent.com/53435085/62825199-db6f0580-bbe2-11e9-99d9-cd542030e589.png)
(Poster made by unknown person)
Stats
Class: Engineer
Health Formula: (((600+n)*(n-1))^1.04)+1900
Lives: 1
Movement Speed: 340 hu/s
Total damage needed to activate rage: 2500
Weapon: Gunslinger

Abilities
Mobility: Teleport, Auto B-Hop(press and hold space bar and he will go fast), Weighdown
Other Abilities:
-Has a rainbow trail when he moves.
-He can hijack a nearby enemy sentry for 6 seconds by pressing Reload button. It costs 50% rage and has 30 seconds of cooldown.
Rage: Stun nearby players for 4 seconds + Players within range has their keypresses scrambled for 7 seconds + Knockback Resistance for 10 seconds + 3 Entangles.(Activate with Middle Mouse button)

His own subplugin is included in his download file.

Download
http://www.mediafire.com/file/orkdy0uuplm2kfe/Beep_Man%2528maxnus_ver%2529.zip/file

2. Electromaniac
![electromaniac](https://user-images.githubusercontent.com/53435085/62825356-428db980-bbe5-11e9-8e68-4a61807aa334.jpeg)
(Poster made by me, in-game model is blue model)
Stats
Class: Sniper
Health Formula: (((700+n)*n)^1.04)
Lives: 1
Movement Speed: 340 hu/s
Total damage needed to activate rage: 3000
Weapon: Kukri

Abilities
Mobility: Teleport, Weighdown
Other Abilities: None
Rage: Stun nearby players for 5 seconds + Gets Rescue Ranger with 5 shots + Knockback Resistance for 10 seconds.

Download
http://www.mediafire.com/file/os2ybg5bcpwes41/Electromaniac%2528maxnus_ver%2529.zip/file

3. Muselk
![muselk](https://user-images.githubusercontent.com/53435085/62825395-cc3d8700-bbe5-11e9-9b02-044426354bc1.jpg)
(Poster made by unknown person, in-game model is blue model)
Stats
Class: Soldier
Health Formula: (((650+n)*n)^1.04)
Lives: 1
Movement Speed: 340 hu/s
Total damage needed to activate rage: 3000
Weapon: Market Gardener(It has 25% faster swing speed, but has 25% damage reduction against players.)

Abilities
Mobility: Super Jump, Weighdown
Other Abilities: None
Rage: Stun nearby players for 5 seconds(8 seconds for sentries) + Gets either one of 3 Rocket Launchers or one of 3 Shotguns + Gains 520 hu/s Speed Boost for 10 seconds. + Gets Minicrit for 10 seconds.

Download
http://www.mediafire.com/file/dm5i1vqpqwdapju/Muselk%2528maxnus_ver%2529.zip/file

4. Nuclear Scout
![nuclear scout2](https://user-images.githubusercontent.com/53435085/62825440-a2389480-bbe6-11e9-9a93-e7ab1c2ece5a.jpg)
(Poster made by Shitcake Production, in-game model is blue model)
Stats
Class: Scout
Health Formula: (((625+n)*n)^1.04)/2
Lives: 2
Movement Speed: 340 hu/s
Total damage needed to activate rage: 3000
Weapon: Fists(Its weapon name is tf_weapon_bat so it has the same swing speed of Scout's bat and high damage, but has 50% damage reduction to prevent it.)

Abilities
Mobility: Super Jump, Lunge(R to activate, costs 20% rage and has 10 sec cooldown, deals 100 damage to player it strikes), Weighdown
Other Abilities: None
Rage: Stun all sentries for 10 seconds + Changes all of RED players' model to a RED sniper with Anger cosmetic for 10 seconds + Gets Wrangler that can shoot like an Ambassador for 15 seconds. It will do 5 seconds of bleed damage on hit.(Was meant to ignite players, but after Jungle Inferno update it got broken)
Lifeloss Ability: Pauses the game for 5 seconds.

Pause ability and Nightmare rage subplugin is in his download files.

Download
http://www.mediafire.com/file/8v5748buc6s26vs/Nuclear_Scout%2528maxnus_ver%2529.zip/file

5. The Gambler
![the gambler](https://user-images.githubusercontent.com/53435085/62825499-afa24e80-bbe7-11e9-865f-7a4e4500c8a3.png)
(Poster made by Lord Homicide)
Stats
Class: Spy
Health Formula: (((700+n)*n)^1.04)
Lives: 1
Movement Speed: 350 hu/s
Total damage needed to activate rage: 2500
Weapon: Sharp Dresser(It has 50% damage reduction to prevent the high knife damage.)

Abilities
Mobility: Super Jump, Weighdown
Other Abilities: None
Rage: Gets Uber for 6 seconds + Forces everyone(Including the boss himself) to roll the dice for a random effect.

Download
http://www.mediafire.com/file/9woj2zuoz1wfn98/The_Gambler%2528maxnus_ver%2529.zip/file

**Comment by RedTerminal1912** [comment]
I like Gambler

**Comment by MrTheBank** [comment]
Will be adding to Pack # 7.
