### ISSUE TITLE
Fix everything about Intergalactic Maxtrinus (CFG,Model,Sound,Abilitys) And add anther boss in pack 6

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#27]
Intergalactic Maxtinus

![IM post](https://user-images.githubusercontent.com/51502238/62828547-b3e46100-bc13-11e9-9615-a9fdb90c5c9c.jpg)

Weapon : Freedom staff
Mobiliys : Super jump and Weigh-down
Rage : Smites + No knock back + stun Sentry+ Abduction + Hellfire
Lostlife : Matrix attack + stuns
2 lifes

Bacause Old ver is Always Invisibility (Cann't seeing model boss) pls just remove that ver

Download : https://www.dropbox.com/s/zxki7kdh6hls0dt/Maxtrinus.rar?dl=0
I record it
https://www.youtube.com/watch?v=R8IL69Bg750&t=17s

Black Murderer

![black murderer](https://user-images.githubusercontent.com/51502238/62828582-6ddbcd00-bc14-11e9-8aa3-16a8112a7ada.jpeg)

Weapon : Festive Knife
Mobiliys : Super jump and Weigh-down
Rage : Gain 4 teleports + Become Short Invisibility + Gain Festive Ambassador + Stun and Sentry

Download : https://www.dropbox.com/s/1xl9exh6w27d6sa/Black%20Muderer.rar?dl=0

https://www.youtube.com/watch?v=lcAE1tIck6M

White Murderer

![white_murdereredits](https://user-images.githubusercontent.com/51502238/62828625-286bcf80-bc15-11e9-9a61-45e8edc8e82e.jpg)

Weapon :  Knife
Mobiliys : Teleport and Weigh-down
Rage : Uber + Become Short Invisibility + Gain Ambassador + Stun and Sentry

Download : https://www.dropbox.com/s/kp0bnu7ktn90o7x/WhiteMurderer.rar?dl=0

https://www.youtube.com/watch?v=7q0sEShRv0U&t=67s

**Comment by MrTheBank** [comment]
ได้ทำการแก้ Intergalactic Maxtrinus เรียบร้อยและได้ทำการเพิ่ม White Murder และ Black Murder เข้าแพ็คที่ 6
