### ISSUE TITLE
from shitcake

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#28]
Nightmare Sniper
Class: Sniper
Weapon: Bat Hell
Abilities: Charge tele and weigh-down
Rage: Change enermy model, enable friendly fire

[First = Popuko, Second = Pipimi]
Pop Team Epic
Classes: Scout and Soldier
Weapons: Boston bat and shovel
Rage: Crits + haste powerup | powerup + shotgun

Shadow Theif
Class: Spy
Weapon: Sharp dresser
Abilities: Superjump and weigh-down
Rage: Invis, steal weapon

St. Heffe
Class: Heavy
Weapon: Fists
Abilities: Fly and weigh-down
Rage: Fully stun all server, smites
Lose life: Abduct (own Heffe's abduct)

Sun9z
Class: Spy
Weapon: Kunai
Abilities: Superjump and weigh-down
Rage: Uber, crits, no knockback, gain timed ambassador
Lose life: Outline, 7 instant teleport points, gain disguise kit
(Drop revive marker on kill)

The Legendary Laugher v2 
(Replace this one in pack 2)
Class: Spy
Abilities: teleport and weigh-down
Rage: Stun, plauge powerup, outline, gain random weapon
Lose life: Resistances, ion cannon, change model

The Mystery Sinister
Class: Spy
Abilities: Superjump and weigh-down
Rage: Stun, invis, gain big kill
Lose life: Random teleport, gain australium ambassador

[Download](https://www.dropbox.com/s/s53435sm3g4sdjt/Boss%20Pack%20%236%20%28Wave%201%29.zip?dl=0)

**Comment by NamelessTheNueProducer** [comment]
Nightmare Sniper would instakill people with his fireball if he uses the standard witch doctor plugin.
Also LL is in pack 2.

**Comment by Sun9z** [comment]
I like Sun9z :+1:

**Comment by MrTheBank** [comment]
ผมไม่สามารถ Bzip Pop Team Epic ได้นะครับ

**Comment by MrTheBank** [comment]
The Legendary Laugher v2 เพิ่มเข้า Pack # 2 และลบของ v1 ออก

Nightmare Sniper
Shadow Theif
St. Heffe
Sun9z
The Mystery Sinister
ทั้งหมดที่กล่าวมาถูกเพิ่มเข้า Pack # 6 

Pattun กับ Slaughter ถูกแก้ไขเรียบร้อย

ส่วน Pop Team Epic เพิ่มไม่ได้เพราะผมไม่สามารถ Bzip ได้

**Comment by ur5ive** [comment]
Pop Team Epic BZip2 compressed.

[Pop Team Epic bz2.zip](https://github.com/MrTheBank/Maxnus-Freak-Fortress-2/files/3509464/Pop.Team.Epic.bz2.zip)
