### ISSUE TITLE
from reverse #4

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#29]
![luardedit](https://user-images.githubusercontent.com/34367924/62844308-9a621880-bcea-11e9-951a-30c95b39be75.jpg)
Credits poster: me
Demonic Wizard Luard
Class: Scout
health formula: (((520+n)*n)^1.04)/2
Rage Damage 3100
Max Speed: 420
3 lives
Abilities: Maigcteleport , Weightdown,
Passive: Drop revive maker on kill red team 
Rage: stun 4.5s + sentry stun 10 s. + uber 7 s. + Turning People around him to duck for 4s + gain 3 Flying Guillotines + Dodge everything for 10
On lost life: Black fog 30s +Gain 3 Smite + Outline 30s + Infinite jump 30s + Sentry stun 10s + Uber 5s + Reflect 15s
Sub-plugins duck abilities and witchdoctor are include in file

[Download](https://www.dropbox.com/s/30orjlywm3sxrgs/Luard%202.1.4.zip?dl=0)

![commander](https://user-images.githubusercontent.com/34367924/62844629-bd8dc780-bcec-11e9-9ad0-8dba35cdc9d8.jpeg)
Credits poster: Wingvoid
This is alternative version of him, Original one made by Neko T!me
Model by Neko T!me
Sound By WingVoid
Commander Scout
Class: Scout
health formula: (((650+n)*n)^1.04)
Rage Damage 3200
Max Speed: 355
1 live
Abilities: Super jump , Weightdown , Lunge cost 0 rage cooldown 15s
Rage: Summon 4 players + No knock back 7.5s + Precision 10s + Defend buff 8s + Speed buff 8s

[Download](https://www.dropbox.com/s/qy1dar5uit33s9c/Commander%20Scout%20alternative.zip?dl=0)

**Comment by MrTheBank** [comment]
Pack 7

**Comment by Sun9z** [comment]
OwO
