### ISSUE TITLE
จาก _Neko T!me_  Add satori

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#3]
http://www.mediafire.com/file/3jx3m2...xeo/Satori.zip

**Comment by MrTheBank** [comment]
เปิดลิงค์ไม่ได้ครับ @Dablikeneko

**Comment by MrTheBank** [comment]
ไม่มีการแก้ไขให้เป็นลิงค์ที่ถูกต้อง กรุณาสร้าง Issue ใหม่หากต้องการให้แอดบอส
