### ISSUE TITLE
New 11 Bosses 

### ISSUE THREAD

**Issue by PuShitcake** [MrTheBank/Maxnus-Network#38]
Actually wave 1 uwu
(Some boss has revive markers but I forgot to put it sorry :P)

Contains
1.) Heavy Sauce
He has super jump and his rage is Stun and gets gun but this version is a bit different because I added Explosion on rage (for look like in gmod video).

2.) Headquarter Foster
He has super jump and his rage is lock player, crits, and gets gun and he also have 2 lifes. On lose life he can summon HLS and cover map with white fog.

3.) Highleader Soldier
He has super jump and his rage is speed up, gets random weapon, cover map with white fog and he also have 2 lifes again. On lose life he gets successfully resistances and when he kills someone, he gain 5 rage meter.

4.) MrTheBank
Ya know him alright? He has super jump and his rage is Ion cannon, speed up, overlay 50 baht vip. He has 2 lifes too. On lose life he gain resistances and outline. Don't let him lose! Or your ears will get rape by him.

5.) Xeacring
A final version of "Ruthless Slaughter" he has super jump and his rage is Stun, uber, successfully resistances and he has 2 lifes again yeah. On lose life he can so explosion and geta permanent speed boost.

6.) Sun9z
There is no "final" word for him. This one is actually immortal update forever. He has super jump with his dead ringer but it does invisible not fake death. His rage is uber, crits, gets time limit gun, hell metoror, black fog. He also have 2 lifes. On lose life he can summon his minion with 700 hp and lock all players for 8 seconds (you can nerf this one) and again he gets disguise kit that no one notice it.

7.) Laszeki (I dont know how to write this name)
A legend boss theme. Ultraman scout. He has super jump and lunge and pistol as his passive but his melee deals low damage same as lunge and pistol. His rage is no knockback and haste powerup. He has 2 lifes. On lose life he can stun and gets his gun.

8.) Zarkares
He has super jump and his rage is uber, mini crits, gets random weapon. He has 1 life

9.) The Rock
Another base of berserk boss. He has super jump but he is slow because he is so fat. His rage is no knockback, speed boost, berserk. He has 1 life.

10.) Loftus
Join battle with YAMEROOOO and his own cover song "Diamond Heart". He has super jump and he has a backstab sounds as his passive. His rage is crits, aimbot, gets random gun. He has 2 lifes. On lose life he can dodge and slow the time down with uber.

11.) Nigga Man
Not racist only joke. I warn you.
He has super jump. When start he has a permanent gun as his passive. His rage is gets resistances and upgrade his gun with time limit! He has 2 lifes. On lose life he can change his model and song to looks more like ricardo and gets sticky bomb permanent with dance explosion.

Link download
https://www.dropbox.com/s/exxapdk1hnlby5i/pu_shitcake%27s%20Bosses%20%28Wave%201%29.zip?dl=0

**Comment by MrTheBank** [comment]
done

**Comment by Sun9z** [comment]
omg sun9z story edgy jung kub
