### ISSUE TITLE
1 New Specialized!

### ISSUE THREAD

**Issue by PuShitcake** [MrTheBank/Maxnus-Network#39]
Wave 2 but solo.

The best signature for Maxnus. It's finally fix. The original by our "gongpha". Shoot the true credit to him. :)

Only 1.) Prayut Chan-o-cha
Thai minister is funny gay. He can super jump. His rage is "Stun, Uber, Summon, Overlay". He has 5 lifes, don't ask why it's same as how long he stay as prime minister. On lose life is "Matrix Attack and Building Destruction". 

This boss also use normal super jump ability instead of dynamic jump, I didn't forget to change but gong wants it. :))))

Download link:
https://www.dropbox.com/s/u4pfjozij2x7gi3/pu_shitcake%27s%20Special%20%28Wave%202%29.zip?dl=0

**Comment by MrTheBank** [comment]
done and added to pack # 1, i ri chai ma se
