### ISSUE TITLE
๊็BOSS

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#40]
MONOKUMA
![image](https://user-images.githubusercontent.com/63923202/79656206-f9aeeb80-81dc-11ea-8972-ea8059ce493e.png)

Skill : Jump lunge slam
Rage : smash + slow speed player near him
lose life : explode

BOB THE BUILDER
![image](https://user-images.githubusercontent.com/63923202/79656448-0b908e80-81dd-11ea-9a04-ca5eabb90883.png)
Skill : Jump
Rage : GET PISTON TO SHOOT EVERYONE THAT ONEHITKILL + STUN
No lose life

SHREK
![image](https://user-images.githubusercontent.com/63923202/79655587-cc623d80-81dc-11ea-8f8a-f2849af1cc96.png)
SKILL : JUMP
Rage : STUN + OVERLAY

มีไฟล์ปลั๊กอินแถมด้วยลงทั้งหมดเลยจะขอบคุณมากๆครับ จะได้ไม่ต้องนำไฟล์มาหลายๆครั้ง

https://www.dropbox.com/s/4sdnw9hbvzpby0g/%E0%B8%A3%E0%B8%A7%E0%B8%A1.zip?dl=0

**Comment by MrTheBank** [comment]
Shrek & MONOKUMA added to pack 2, Bob The Builder added to pack 1.
