### ISSUE TITLE
3 bosses not thing more 

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#41]
**Completed Havoc**
He just a weebshit spy :/ i dunno i can't explain info of this boss
2 lives
Passive: Revive marker (exclusive version :3 ) and random crit too!
Rage: stun everyone for 1 sec,sentry stun for 10 sec+Hell Rocket Raid+Increase moving speed and drain speed player than near him+Mini-Crits+Precision+Hell fire rate gun
Lost life: Permanent no knock back condition + Dodge attack damage for 6 sec
Plugins needed:
ff2_dynamic_defaults
ff2_otokiru_wc3
default_abilities
ff2_sarysamods4
m7_abilities_extended
ff2_sarysapub3
ff2_movespeed
ff2_tfcond
ff2_tfcond2
shadow93_abilities
ff2_sarysamods3
ff2_sarysamods
mann_up_abilities
ff2_blockdropitem

Poster:
![havoc](https://user-images.githubusercontent.com/34367924/79657667-6629ea80-81dd-11ea-9c9d-a69ad7edec38.jpg)

[Download](https://www.dropbox.com/s/blh6kx9ec9gpyb8/completed%20havoc.zip?dl=0)

**Holiday Undead Medic**
uh zombie?
2 lives
Passive: he can regen his life for 30sec it will increase 90 sec everytime he lost his life and can random crit (again)
Rage : Stun player near him + instant kill player near him + Gain a crossbow
Plugins needed:
ff2_dynamic_defaults
ff2_otokiru_wc3
default_abilities
ffbat_defaults
ff2_sarysamods
ff2_tfcond
shadow93_bosses
ff2_sarysamods6

No poster :(

[Download](https://www.dropbox.com/s/u3rf4epgwl36u0d/Undead%20medic.zip?dl=0)

**Eternity Edge**
not edgy :|
He have hook that deal no damage to player (bleeding too)
Passive: **Random crits**
Rage: Stun players and Building + Dodge damage + Destory building in range + Gain plague powerup (don't think you can drop it :3 becuz i BLOCK it cannot be drop by normal expect you did something that really worst)
Plugins needed:
ff2_dynamic_defaults
ff2_otokiru_wc3
ff2_movespeed
ff2_tfcond
ff2_sarysamods

No poster :(

[Download da yo](https://www.dropbox.com/s/ktkw3qd4ijyttxi/Eterntity%20Edge.zip?dl=0)

![yus](https://user-images.githubusercontent.com/34367924/79667148-1ef12900-81e0-11ea-9c50-aad94c5265e0.jpg)

**Comment by MrTheBank** [comment]
**Eternity Edge** has been added to Pack 1 **Completed Havoc** & **Holiday Undead Medic** have been added to Pack 2.
