### ISSUE TITLE
Boss for Server #4 Bosses

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#42]
Black Murderer
Ability - Super jump and weight down
Rage - Stun + Stealth + Gain Haste Power up + vaccinator + outline + Gain Ambassador + Gain Points teleport
Passive - Dark fog all time

![image](https://user-images.githubusercontent.com/51502238/79691300-e35e6980-8288-11ea-93c7-60db448dba02.png)
 
White Murderer
Ability - Teleport and weight down
Rage - Stun + Stealth + Stealing Weapon 900 M + Stole weapon class 
Passive - White fog all time + Revive maker 

![image](https://user-images.githubusercontent.com/51502238/79691372-4ea83b80-8289-11ea-828b-8110b4efbd8e.png)

Download (Duo cfg in file)
https://www.dropbox.com/s/0yef12vdbwz68gl/black%20and%20white%20duo.rar?dl=0

Deadshot sniper
Weapon - Awp + Bow (Use M3 to change Weapon)
Ability - weight down
AMS Rage
Outline
Stun enemies
Slow enemies
Stop move moment enemies and Hidding model
Breaker Mode (Gain power up + Uber + Crits)

Model when use AWP
![image](https://user-images.githubusercontent.com/51502238/79691513-3be23680-828a-11ea-8cb9-481f455b9f73.png)

Model when use Bow
![image](https://user-images.githubusercontent.com/51502238/79691535-659b5d80-828a-11ea-802d-2138d4b50601.png)

Download
https://www.dropbox.com/s/pr44y39smicgmw3/deadshot%20v2.rar?dl=0

Supplugins for boss
m7_abilities_extended -https://forums.alliedmods.net/attachment.php?attachmentid=171927&d=1540238636
ff2_movespeed - https://forums.alliedmods.net/showpost.php?p=2304889?p=2304889
ff2_tfcond - https://forums.alliedmods.net/showpost.php?p=2304889?p=2304889

The Mysterious Hunter
2 lifes
Ability - Teleport and weight down
Rage - Gain Festive Ambassador + Crits short time + Quick Fix Effect + Stun and Sentry + Dark Fog
Lostlife -Change Theme sing + Change melee weapon + Gain Big killer + Gain Teleport 8 points + Quick Fix all time + Mark death on enemies
Passive - Revive maker 100 second

![image](https://user-images.githubusercontent.com/51502238/79691869-16562c80-828c-11ea-90ac-d5835e57e31f.png)

Download
https://www.dropbox.com/s/ozefqgm01oxsrn5/n1kospy.rar?dl=0

Thank you!

**Comment by MrTheBank** [comment]
All of them have been added to **Pack 3**.
