### ISSUE TITLE
a boss

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#43]
**Syn Luke**
2 lives
Passive: Revive marker and random crit hits
Rage: Crit+Stun+Gain Diamondback + No knock back + Fog
Lost life: Theme change + Freeze players + Martix
Plugin Needed:
ff2_dynamic_defaults
ff2_otokiru_wc3
shadow93_abilities
ff2_fog
ffbat_defaults
ff2_tfcond
default_abilities
m7_abilities_extended
ff2_1st_set_abilities
ff2_servercommandrage
ff2_sarysamods

Poster:
![luke_edit](https://user-images.githubusercontent.com/34367924/79695409-ea917180-82a0-11ea-9453-13f9c60efbe3.jpeg)

[Download](https://www.dropbox.com/s/17zdvwnfsc20b00/New%20Syn%20Luke.zip?dl=0)

![nanitheheck](https://user-images.githubusercontent.com/34367924/79695428-0268f580-82a1-11ea-99be-91435fdd814b.jpg)

**Comment by Reversesniper** [comment]
-Fix missing texture and download
-Update config

**Comment by MrTheBank** [comment]
Added to Pack 3
