### ISSUE TITLE
Sun9z's new outtromusic (2 outtro) / New Boss (Not True Administrator)

### ISSUE THREAD

**Issue by Sun9z** [MrTheBank/Maxnus-Network#46]
Sun9z
"The Most Active Boss forever forward updating"
------------------------------------------------------
Update
------------------------------------------------------
- New 2 Outtromusics [ win ( new )/ lose ( new ) / stalemate ( old ) ]
- Nothing Buff
- VIP Only 50 Baht.
------------------------------------------------------
Not True Administartor  ( already nerf + updated )
------------------------------------------------------
After 2 years, maxnus is back and now tfoc is closing for the sake of maxnus but is nta gonna take a seat come back to become a new moderator?
He only lives once just like i said.
------------------------------------------------------
Ability
------------------------------------------------------
+ Delayable Damage
+ Underwater Speed
+ Rage Cond
+ Uber
------------------------------------------------------
Passive - Revive markers
------------------------------------------------------
AMS Rage
------------------------------------------------------
- Outline ( Cost 0 )
- Vaccinator [ Random Effect ] ( Cost 25 ) 
- Invisible ( Cost 50 )
- Random Weapon [ Sniper and Rocket Launcher ] ( Cost 75 )
- Successfully Resistance ( Cost 100 )
------------------------------------------------------
u can just ignore the boss but the boss have very awesome thing about maxnus tho <3
and pls update the sun9z sound

[Download](https://www.dropbox.com/s/uyh616i9kehbc52/Sun9z%20next%20admin.rar?dl=0)

**Comment by Reversesniper** [comment]
i'm making new sung with unusual effect fak

**Comment by Sun9z** [comment]
i only update sounds xd

**Comment by Reversesniper** [comment]
okei XD OeO

**Comment by MrTheBank** [comment]
Updated Sun10-1z sounds and added Not True Administrator to Pack 3.
