### ISSUE TITLE
Fast "Shin" Fix!

### ISSUE THREAD

**Issue by PuShitcake** [MrTheBank/Maxnus-Network#47]
Boss made by Loftus.
And it was fixed by me.

"Loftus the DDoSer" -Loftus 2019-2020

Link download:
https://www.dropbox.com/s/fd9enq74exx3t2c/Shin%20%28Shitcake%27s%20Fix%29.zip?dl=0

(I'm really sorry for everything)

**Comment by ur5ive** [comment]
no, client still crashes.
