### ISSUE TITLE
Fix N1ko spy and Black murderer 

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#48]
I give only cfg file If them have some problem.Please report it to me and I will fix or rework Thank you
Download
https://www.dropbox.com/s/kx3isi5nmvmdq5w/fix%20cfg.rar?dl=0

**Comment by RedTerminal1912** [comment]
รบกวน check file white murderer ด้วยครับเพราะไม่เห็นอยู่ใน pack 3

**Comment by MrTheBank** [comment]
![image](https://user-images.githubusercontent.com/16158569/80315918-eb884d00-8824-11ea-8c39-b590f99a37a7.png)
