### ISSUE TITLE
"Shin" fix v4?

### ISSUE THREAD

**Issue by raykoshima** [MrTheBank/Maxnus-Network#49]
Sorry for everything
but i add new backstab sound

"Loftus the DDoSer" -Loftus 2019-2020
shitcake offline i do แทน
Link download:
https://www.dropbox.com/s/1kgvrfmc1ex4aa2/Shin%20%28Shitcake%27s%20Fix%29.rar?dl=0

**Comment by MrTheBank** [comment]
No, It still make client crash.
