### ISSUE TITLE
จาก shit cake ฝากมางับ

### ISSUE THREAD

**Issue by Mrleft4deathtwo** [MrTheBank/Maxnus-Network#5]
Sun9z is spy with Kunai and ofc he uses superjump, his rage is uber + crits + gain ambassador that act like rocket with 2 ammo, but on his lose life he can cover the map with black fog and diguise! His sound is like meme you know if you hear it 
p.s. He has low health

Pop Team Epic DUO and Killing Mann can read in fourm it's 100% balance you know

All another information is in "readme" file 

Download link:
https://www.dropbox.com/s/sr7x5ma21cdjsr1/3%20new%20bosses.zip?dl=0

**Comment by gongpha** [comment]
Will Sun9z coming ?

**Comment by MrTheBank** [comment]
ผม bzip ไฟล์ไม่ได้นะครับ รบกวนนำไฟล์ที่มี bzip มาด้วยหรือบอกโปรแกรม bzip ให้ผมก็ได้

**Comment by MrTheBank** [comment]
ไม่มีการตอบรับ
