### ISSUE TITLE
RTX boss and fix syn luke

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#50]
**Syn luke**
-Fix materials download

[Download](https://www.dropbox.com/s/uvhnkkwx8aenvl8/lukey%20fix.zip?dl=0)

**RTX Edgy Lord**
*Warning this boss contain alot of memes stuff and it can destroy somepeople brain*
Class: sniper
Max speed: 380
Health formula: (((740+n)*n)^1.04)/2
Can random crit
Disable triple damage
2 lives 

AMS rage
Overlay 
Fog (invisble+outline)
Gain crit,no knock back,Uber for 5 sec and stop all players movement for 5 sec too
Dodge damage for 15sec
Random weapons (7 weapons)

Lost lives
Beam+Matrix+Freeze+Stun

Alternative fog include

![sexsun](https://user-images.githubusercontent.com/34367924/80302134-70964680-87d2-11ea-9340-0cfee80db6c0.jpg)

[Download RTX2080SUPER Ti here](https://www.dropbox.com/s/a2xgmt4o3sj5zcb/RTX2080SUPER%20Ti.zip?dl=0)

**Comment by Reversesniper** [comment]
**RTX Edgy Lord**
-Add true admin and myst scout weapons to random weapon rage
-Add new sound to killspree slot
-Reduce time of dodge rage

**Comment by Hidden-1** [comment]
hohoho no true admin in maxnut

**Comment by Reversesniper** [comment]
1 ammo :/ and 1 in 9 weapon 
need a lot of luck

**Comment by Hidden-1** [comment]
that's seem fair but what bout the shield

**Comment by Reversesniper** [comment]
he isn't true admin LOL

**Comment by Hidden-1** [comment]
**ok soldier**

**Comment by MrTheBank** [comment]
Added new Syn Luke cfg to server

**Comment by MrTheBank** [comment]
added rtx edgy lord
