### ISSUE TITLE
แก้เสียง เสียงเพลงตอนจบเกม

### ISSUE THREAD

**Issue by Sun9z** [MrTheBank/Maxnus-Network#51]
**เรื่อง**        **ขอความอนุเคราะห์แก้ไขข้อมูลเสียง** **บอส** **ซันเก้า**

**เรียน**       **มิสเตอร์เดอะแบ๊งค์**

ด้วยในวันที่ 22 เดือน เมษายน ผมได้ทำการ อัปเดท เสียง ซันเก้า ใหม่ โดยมีด้วยกัน 2 เสียง ใหม่ สำหรับ ตอนจบเกม ซึ่งทั้งหมดนั้น ใช้ได้แค่ 1 เสียง เพราะ เนื่องจากอีกเสียงนึง ผมได้ทำการเขียน [ outtromusis_win ] แต่ไม่ใช่ [ outtromusic_win ] จึงทำให้เกิดข้อผิดพลาด เกมไม่สามารถ รับรู้ข้อมูลได้

จึงขอความอนุเคราะห์จาก มิสเตอร์เดอะแบ๊งค์ ในการแก้ไขข้อมูลของบอส ซันเก้าด้วย และ ให้ทำการลบ outtromusis_win ใน fastdl และ ใน sounds ของ server ด้วย

จึงเรียนมาเพื่อโปรดพิจารณา และขอขอบพระคุณล่วงหน้ามา ณ โอกาสนี้ หากท่านมีข้อสงสัยประการใด สามารถติดต่อสอบถามได้ที่ Discord Sun9z#9267

[ดาวน์โหลด เสียง outtromusic_win](https://www.dropbox.com/s/vnlbo0r2ugt7g1i/Sun9z%20cant%20hit%20p%20without%20mrthebank.rar?dl=0)

**Comment by MrTheBank** [comment]
**สวัสดีครับ**

**คุณ** ซันเก้าซี

คำขอร้องในการแก้ไขข้อมูลของบอส ซันเก้าซี ถูกอนุมัติโดยผู้บริหาร และได้ทำการอัพโหลดไฟล์ขึ้นเซิฟเวอร์เรียบร้อยครับ

ขอบคุณครับ
MrTheBank - ผู้บริหาร
