### ISSUE TITLE
Add Boss #Nameless boss and my boss

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#52]
The Unidentified Producer
Stats
Class: Scout
Health Formula: ((765+n)*n)/2
Lives: 2
Movement Speed: 346 hu/s
Total damage needed to activate rage: 3460
Weapon: Batsaber(Weapon name is tf_weapon_bonesaw so it doesn't have extra damage and fire rate)
Abilities Rage - (Sommon Nue + Gain scatter gun + stun)

![image](https://user-images.githubusercontent.com/51502238/80282788-94f41380-873d-11ea-91d1-e771be0bf721.png)

Download
https://drive.google.com/open?id=1an45eTpg6IH2ifPBvGLf_gtKcqVYOMoK

Nue Houjuu
Stats
Class: Spy
Health Formula: (((700+n)*n)^1.04)
Lives: 1
Movement Speed: 340 hu/s
Total damage needed to activate rage: 3500
Weapon: Festive Knife(It has 50% damage reduction to players to prevent the extra damage on knife weapons. Also the backstab makes her disguise and once she's on disguise, she's immune to fire attacks.
Abilities Rage - ( Stun all sentries for 9.5 seconds + Goes invisible for 10 seconds(Her attack exposes her model for a sec) + Makes Abduction around her(10 sec)

Download
https://drive.google.com/open?id=1Vuy4Ui08Zh61TrfHH_9dkGLPUzvmtwgA

IF
Stats
Class: Scout
Health Formula: (((700+n)*n)^1.04)
Lives: 1
Movement Speed: 360 hu/s ~ 450 hu/s(The less health she has, the faster she goes)
Total damage needed to activate rage: 3500
Weapon: Three Rune Blade(Even it's weapon name is tf_weapon_bat, it has 45% slower swing speed and 50% damage reduction to players.)
Abilities Rage - (Uber + Stun + Quick Fix fix + Speed)

Download
https://drive.google.com/open?id=1K9rfJ2W7tytuAldfAyOVCctzk9AiEiHC

Scarlet Sisters
-Remilia Scarlet
Stats
Class: Spy
Health Formula: (((760+n)*n)^1.04) / Duo version: (((760+n)*n)^1.04)/2.8
Lives: 1
Movement Speed: 340 hu/s
Total damage needed to activate rage: 3000 / Duo version: 2500
Weapon: Three Rune Blade(Its weapon name is tf_weapon_knife so it doesn't have faster swing speed. Also it bleeds player for 5 seconds and drains 5% of Medic's Ubercharge and Spy's Cloak Meter on hit, but has 60% damage reduction to reduce the knife's extra damage.)
Abilities
Mobility: Super Jump, Weighdown
Other Abilities: Bat Spell(R to activate, costs 30% rage and has 20 sec cooldown.)
Rage: Stun nearby players for 5 seconds(7 sec for sentries) + Gets 1 clip Loch-n-Load that shoots Gungnir(Her iconic spear, acts like a direct hit rocket with a massive damage) projectile.

-Flandre Scarlet
Stats
Class: Spy
Health Formula: (((600+n)*n)^1.04) / Duo version: (((700+n)*n)^1.04)/2.8
Lives: 1
Movement Speed: 360 hu/s
Total damage needed to activate rage: 3000 / Duo version: 3000
Weapon: Three Rune Blade(Its weapon name is tf_weapon_shovel so it doesn't have extra damage and swing speed. Also it has extra 50% melee and does crit to players who have marked for death effect. But it has 30% damage reduction to players.)
Abilities
Mobility: Super Jump, Weighdown
Rage: Stuns all sentries for 10 seconds + Explosion around her after a few seconds.(Human Sentry Buster Rage) + Rock Rage(No Knockback + Instakills whoever she touches, 10 sec) + Defense Buff(10 sec) + 450 hu/s Speed Boost(10 sec) + Summons 3 clones.
The clones have 250 health with Three Rune Blade with extra 100% melee range. It bleeds player for 1 seconds and gives marked for death effect on hit. But it has 99% damage reduction.
Also the clones have 50% knockback resistances and damage resistances from ranged sources, 100% higher jump height, and can't be backstabbed.
But you can't summon clones again on rage if either of them are still alive. Only maximum is 3.

Download
https://drive.google.com/open?id=1cq_ZSQeKcIi4ysKi-H8eP_cvGpwzeLiY

Megumin
Stats
Class: Sniper
Health Formula: (((700+n)*n)^1.04)/2
Lives: 2
Movement Speed: 300 hu/s
Total damage needed to activate rage: 3500
Weapon: Freedom Staff(but when the round starts, her melee changes to the ranged projectile attack)
Abilities
Mobility: Super Jump, Weighdown
Rage: Stuns all sentries for 10 seconds + Explosion around her after a few seconds.(Human Sentry Buster Rage)
Lifeloss Ability: Different type of Explosion(Seeman Rage) + Model Change

Download
https://www.dropbox.com/s/ptlahu7u742polf/megumin.rar?dl=0

Japanese style spy
Class spy
Lives 2
Rage - (Gain buff + Gain Gun + Stun and stun sentry around boss)
On lostlife - (Dark fog + Vc)

Japanese Winter sniper
Class Sniper
Lives2
Rage - (Stun + Freeze + Hide model + White fog)
On lostlife - (Gain Bow all life + sommon jss)

Download
https://www.dropbox.com/s/xskpd34ndgtswro/JSS%20and%20JWS%20DUO.rar?dl=0

MLG Demoman
Ability Super Jump and Weight down
Rage - (Overlay + Explosion + Gain Gun)
Lostlife - matrix

Download
https://www.dropbox.com/s/0e018gxn2ge2c3u/mlg%20demoman.rar?dl=0

Starlord
Lives 2
Ability Super Jump and Weight down
Rage - (Explosion + Gain Gun + Stun)
Lostlife -  (Sommon megumin + Explosion)

Download
https://www.dropbox.com/s/8f2v7g29bi4rgab/starlord%20guys.rar?dl=0

Summer Demo
Ability Super Jump and Weight down
Rage AMS

Download
https://www.dropbox.com/s/xhiu6r6mzjyz4pb/summer%20demo.rar?dl=0

Outlaw spy
Lives 2
Ability Super Jump and Weight down
Rage - (Stun + Gain Gun + Hidden model)

Outlaw Sniper
Ability Super Jump and Weight down
Rage - (Stun + Gain Gun + Gain Crits)

Download
https://www.dropbox.com/s/gp8rrnbv56uw49n/outlaw%20spy%20and%20outlaw%20sniper%20duo.rar?dl=0

Legendary Laugher
เราจะขาดคน IQ ต่ำคนนี้ไปไม่ได้ หรือได้วะ?
Lives 2
Ability Super Jump and Weight down
Rage - (Hellfire + Berserk + Quick fix)
Lostlife - (Gain Enforcer + ioncannon)

Download
https://www.dropbox.com/s/dp3iv4gshbzhtkp/new%20legendary%20laugher.rar?dl=0

Minecraft Engineer
Ability Super Jump and Weight down
Rage - (ture everyone to diamond + diamond rain)

Download
https://www.dropbox.com/s/3ergtg0v25zpd2n/minecraft%20engineer.rar?dl=0

**Comment by MrTheBank** [comment]
Added all of Nameless's bosses

**Comment by MrTheBank** [comment]
Added Japanese Style Spy, Japanese Winter Sniper, MLG Demoman and Summer Demo

**Comment by MrTheBank** [comment]
Done.
