### ISSUE TITLE
ขอความกรุณาเนิฟ + fix บอสครับ (ให้ Agent อ่านเถอะครับ Recommend)

### ISSUE THREAD

**Issue by PuShitcake** [MrTheBank/Maxnus-Network#53]
50/555 หมุ๊่ 50
                                           ฏำบลวิ๊ไฮพิ๊ จ.วิ๊ไอภิ๊
                                           ฮ.วิ๊ไอภิ๊ 55555

                     วัลธิ๊ฆ์ 25 เฒษ๊ญฯ 2563

เฬอื่บ์ลง ฆอคว๊ฒอฯุเคร๊๊ห์เนิ๋ฟบอษฆองพ๊กผฒ

เริ๊ญฯ ลอร์ฎแบงค์

เนื่ฮงนั๊บ์ษ์ยวัลษ์ธิ๊ฆ์ณิ๊ ผฒไฎ๊เห็ณบอษโอพิ๊หล๊ญฏัว กร๊ผฒจึงไฎ๊ธำก๊รเนิ๋ฟฏัวพ๊กฯั๊ณ

จึงฆอคว๊ฒอนุเคร๊๊ห์จ๊กลอร์ฎแบงค์ช่วญณำคฮณฟิคธั๊งหมฎธิ๊ฆ์กร๊ผมไฎ๊เณิ๊ฟณั๊น นำใษ่เซิฟฎ๊วยครั๊ผฌ์
(หวังว๊พ์แฮฎจ่ฮ่๊นพ๊ษ๊สก๊อยฌ์ออกน๊ครั๊ผษ์ เภร๊๊เฮเจ๊ฯยังเคญเฆิ๊ญฯเร่รร เฮ๊กดลีร์)

ฎ๊วญคว๊มเค๊รภอย่๊งษุ๊ง
ลฮร์ฎแบงค์ ห๊๊ษิบบ๊ธ

Link download:
https://www.mediafire.com/file/js7oswcp4vjvw2y/Som_Boss_Ching_Ching_Na_Ha_%28Fix%29.zip/file

*ง่ายๆครับ Nerf บอสครับ 5555

**Comment by Sun9z** [comment]
กูเข้าใจนะว่ามึงเป็นสก๊อยแต่อย่าทำตัวอย่างงี้เลยนะเพื่อนก่อนที่มึงจะโดนกูตัดเพื่อนและโดนตัดเป็นแอดมิน

**Comment by PuShitcake** [comment]
> กูเข้าใจนะว่ามึงเป็นสก๊อยแต่อย่าทำตัวอย่างงี้เลยนะเพื่อนก่อนที่มึงจะโดนกูตัดเพื่อนและโดนตัดเป็นแอดมิน

ฆอโธษน๊ครั๊ผ ฏ่อปั๊บ์ยผฒจ่มรั๊ล์ซ์ยเฆิ๊ญนพ๊ษ๊สก๊อยอิ๊กเร่รฬซ์ฬครั๊ผ

**Comment by Reversesniper** [comment]
magic imma sent my nerf ver bruh

**Comment by gongpha** [comment]
ผมนี่ประเมินเลย

- [ ] เหมาะสม
- [ ] โคตรเหมาะสม
- [x] คิดได้งัย

**Comment by ur5ive** [comment]
`are you guys autism?`

**Comment by PuShitcake** [comment]
Change log:
- Bumped update links. (Fix Spyper)

**Comment by PuShitcake** [comment]
Changes log:
- Fix Loftus's background music. (Make it lounder)
- Nerf more bosses.
- readme.txt

**Comment by Hidden-1** [comment]
**very good**

**Comment by MrTheBank** [comment]
![image](https://user-images.githubusercontent.com/16158569/80617588-7eff8f00-8a6c-11ea-9389-10de93206d8e.png)

**Comment by PuShitcake** [comment]
Sorry, Dropbox actually drunk nowsday.

New download link:
https://www.mediafire.com/file/js7oswcp4vjvw2y/Som_Boss_Ching_Ching_Na_Ha_%28Fix%29.zip/file

**Comment by MrTheBank** [comment]
done
