### ISSUE TITLE
----------BEWARE YOUR BUTT----------

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#56]
### **PLUGIN แถมให้ไปใน DOWLOAD แล้ว**

**Stripper Soldier**
![image](https://user-images.githubusercontent.com/63923202/80820043-5c05e400-8c00-11ea-9ae8-d354385f055c.png)
Super jump rage will give ironbomber and make everyone sticky

**Cuddly Heavy**
![image](https://user-images.githubusercontent.com/63923202/80820192-a12a1600-8c00-11ea-93f9-e12132106fbf.png)
Superjump rage will make him uber and everyone got stun
SPECIAL ATTACK [ HUG ]

**Takakazu Abe**
![image](https://user-images.githubusercontent.com/63923202/80820661-83a97c00-8c01-11ea-8905-3693f61adc55.png)

Superjump rage will make him fast gold digger

### **https://www.dropbox.com/s/o89owb2gcs7op9h/byb.rar?dl=0**

**Comment by MrTheBank** [comment]
Added.
