### ISSUE TITLE
Solo Boss Wave #4

### ISSUE THREAD

**Issue by PuShitcake** [MrTheBank/Maxnus-Network#58]
### The Legendary Laugher
   **Original Remastered**

![lledit](https://user-images.githubusercontent.com/63900170/81031301-04909e00-8eb6-11ea-822e-286339649c22.png)

>Here's come with full toxic, more than version 1

His abilities.
   Super Jump: Hold right click, look up and release it.
   Weigh-down: Hold CTRL and look down.

His rage is (Hellfire + Outline + Plague Powerup + Gain The Enforcer with 3 ammo) 
   Press medic to active.

On lose life is (Ion Cannon where he standing)
   Active on lose life.

**Download link:** 
 Dropbox: https://www.dropbox.com/s/r9uppdxzqpmparb/Legendary%20Laugher%20-%20Original.zip?dl=0
MediaFire: https://www.mediafire.com/file/ux3ek34mcspoyez/Legendary_Laugher_-_Original.zip/file

**Comment by MrTheBank** [comment]
Added to Pack 2
