### ISSUE TITLE
Nerf and Make Balance For Good Boss#N1ko spy,Deadshot,Summer demo,Jss and Jws,MLG Demo

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#59]
Nerf Hp N1ko spy,Deadshot,Summer demo,Jss and Jws,MLG Demo
เพิ่ม plugins Dot ใน file นะฮะ
https://www.dropbox.com/s/mvqxoe5klyp8zfa/fix%20boss.rar?dl=0

**Comment by MrTheBank** [comment]
done, sorry for late response.
