### ISSUE TITLE
จาก ZELL

### ISSUE THREAD

**Issue by LLEZ** [MrTheBank/Maxnus-Network#6]
พยายามหาบอสที่น่าสนใจหน่อย
Greed
http://www.mediafire.com/file/g4yr07emrl2y67s/Greed.rar
Class: Spy
Weapon: The Black Rose
Abilities: Super Jump, Weighdown, Rage
Boss deals 25% less damage and attacks 10% slower, but he slows his enemies on hit and turns his victims to gold (because he's Greed)
On rage, he ubers for 3 seconds, gains random buffs for 5 seconds, and delivers an overlay of dollar bills to the whole server for 7 seconds and a half (also because Greed).
Necessary plugins:
-M7's Plugin (Use the one that comes with Killing Mann for the updated version)

The Templar
https://www.dropbox.com/s/udjgemw9z8b4h6n/The%20Templar.rar?dl=0
Class: Medic
Weapon: Ubersaw. Swings half as slow, but deals 50% more damage.
Abilities: Super Jump; Weighdown, Rage
Rage: Teleports to a random player, forces the other players into monochromatic view (black and white) for 15 seconds, and disguises as a RED team member during that time. Rage sound also plays to the whole server. This is to try and confuse the RED team into figuring out where the boss is, adding a little bit of challenge to them.

MLG Heavy
https://www.dropbox.com/s/t1dfsz5d0afahl1/MLG%20Heavy.rar?dl=0
Class: Heavy
Weapon: Eviction Notice
Abilities: Super Jump; Weighdown and Rage
Boss has a shotgun that mini-crits whoever is airborne (good for jumping soldiers and demos, also those annoying scouts), and turns people to gold when he kills them, but has a very poor firing speed, so use it wisely.
On rage: Boss marks everyone in the map for death, and speeds up almost faster than a scout for 9 seconds. (duration of rage sound)
Don't worry. Unlike the MLG Sniper boss, this boss doesn't have ear-raping sounds.

Dankineer
https://www.dropbox.com/s/8cx1o4qa7vj87yd/Dankineer.rar?dl=0
Class: Engineer
Weapon: Golden Wrench
Abilities: Dynamic Super Jump; Dynamic Weighdown; Rage
Super Jump: 1.5 seconds to charge, 5 seconds cooldown.
Rage: Get a Weedgun that shoots incredibly slowly. Also gets a lightning bolt charge.
3 lives.
On life loss: Get a Super Headshot Rifle which deals reduced damage on bodyshot, but higher headshot damage, and also performs explosive headshots. Can only fire while zoomed in.

Swag Spy
https://www.dropbox.com/s/3ysbv4hp3ssl9nb/Swag%20Spy.rar?dl=0
Class: Spy
Weapon: Knife
Abilities: Super Jump; Weighdown; Rage
Rage: Creates a flashy fog with mixed colors around and makes the RED team dance helplessly.

Textureless Spy(น่าลองสุดๆ)
https://www.dropbox.com/s/gh4dwh31yfr3kxx/Textureless%20Spy.rar?dl=0
Class: Spy
Weapon: Knife
Abilities: Teleport, Weighdown, Rage
Rage ubers the boss for 5 seconds, stuns everything around for 5 seconds and spawn many copies of the disturbing textureless spy, which have no weapons and can't kill. These are to confuse the RED team into finding the real one.
He has 10 lives (yes, 10)
When he loses one, the RED team's screens gets filled with a glitchy visual for 10 seconds.
On top of that, while the boss is on the map, the area around the players and the boss is darkened.

**Comment by MrTheBank** [comment]
The Templar **ไม่ผ่าน** สกินเสียนะครับ

**Comment by MrTheBank** [comment]
MLG Heavy **ไม่ผ่าน** Rage เสียและมีบัคของปืน

**Comment by MrTheBank** [comment]
Greed, Dankineer, Swag Spy, Textureless Spy **ผ่าน** จะถูกเพิ่มในบอสแพ็คที่ 5 (เร็วๆนี้)
