### ISSUE TITLE
Another VGA boss 

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#60]
**RX Cool Lord**

> Warning this boss contain alot of memes stuff and it can destroy somepeople brain

Class: Medic
Max speed: 380
Health formula: (((740+n)*n)^1.04)/2
Can random crit
Disable triple damage
2 lives

Ability management system 
>Dark fog+Invisible+Outline
>Crits+No knock back+Defen buff+Death mark all players
>Increase speed to maxinum and drain players speed around him
>No knock back+Blast and Fire defend buffs
>Random weapons

Lost life
Martix+Aimbot

![ze](https://user-images.githubusercontent.com/34367924/81091565-9c7b9f80-8f29-11ea-8e65-ed09f7cc6e57.png)

[DOWNLOAD VGARX5700XTVEGA64 HERE](https://www.dropbox.com/s/vog4zzmg7k4dk3h/RX5700XTVEGA64.zip?dl=0)

![mystery_sight_lordbank_meme](https://user-images.githubusercontent.com/34367924/81091954-1e6bc880-8f2a-11ea-9260-92e912290b44.jpg)

**Comment by MrTheBank** [comment]
Added.
