### ISSUE TITLE
-----HELL REACH-----

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#61]
**_SUBPLUGIN แถมใน DOWLOAD แล้ว_**

### **Demo Samedi**
![image](https://user-images.githubusercontent.com/63923202/81205003-47f12680-8ff4-11ea-8838-e25b45b8440d.png)

- RAGE : STUN,SUMMON
- LOST LIFE : MATRIX

### **YOUR WORST NIGHTMARE [REMASTERED]**
![Y0ur w0rst n1ghtm4r3](https://user-images.githubusercontent.com/63923202/81206177-ef228d80-8ff5-11ea-819f-94f82e147cff.png)

- PASSIVE : SLOWDOWN PLAYER
- SPECIAL : TELEPORT
- RAGE : SCRAMBLE PLAYER POSITION,MOVE SPEED,STUN

### **The Bloodrider**
![image](https://user-images.githubusercontent.com/63923202/81206563-7d970f00-8ff6-11ea-8b06-e6feae4fa7e2.png)

- GRENADE HELL
- GIVE HOOK TO EVERYONE
- RAGE : - Switches to one of nine different classes
              - Gets one of five random Grenade Launchers
              - Gains Minicrits, the Defensive and Regen buffs
- LOST LIFE : - Gains Ubercharge and Crits
                     - Gains one of five different powerups
                     - Switches to one of nine different classes
                     - Gets one of five random Grenade Launchers

### **Father of All / The Blitzkrieg / 弾幕ドクター**
![image](https://user-images.githubusercontent.com/63923202/81207280-8805d880-8ff7-11ea-9a37-5df75d092f9b.png)
- ROCKET HELL
- ONLY RANDOM TO PLAY THIS BOSS

### **_DOWLOAD : https://www.dropbox.com/s/f41ppnygaa5frtu/H3LL.zip?dl=0_**

PS. อยากเปิดไปใส่ hidden ใน cfg เป็น 0
PS2. Blitzkriegอันนี้้ ver batfox ไม่โกงไม่ต้องเป็นห่วง ส่วน bloodrider ก็ล้มได้ถ้าช่วยกัน

**Comment by Hidden-1** [comment]
**yeah.. blizkrieg and bloodrider**

**Comment by PuShitcake** [comment]
ลองคิดผลระยะยาวสำหรับ blitz และ bloodrider

**Comment by RedTerminal1912** [comment]
Hidden "1"

**Comment by Hidden-1** [comment]
what's 1

**Comment by MrTheBank** [comment]
Added only Demo Samedi and YOUR WORST NIGHTMARE.
