### ISSUE TITLE
Add Boss เพิ่ม#For another and Next pack

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#63]
1.GTX Toxic Lord

Model
![image](https://user-images.githubusercontent.com/51502238/81419288-3a64a980-9178-11ea-860e-305840db66be.png)

![image](https://user-images.githubusercontent.com/51502238/81419450-71d35600-9178-11ea-81ad-6a880ec328b6.png)

Ability : Super Jump And Weigh-down
Lives : 2
AMS Rage List
1.Fake Dead Ringer
2.Outline | Do spot Low IQ people
3.แง๊นๆๆๆ | Speed moving like เด็กไทยอนาคตไกล
4.มีคนก๊อปพี่เต้เรา | Make model Low IQ people like Model Boss
5.Do something Toxic here here | Get Toxic Power and Low IQ people ได้งงแดกกับสิ่งที่เห็น
6.ระเบิดเวลาาาาาา อ๊ากกกกกกกกกกกกกกกกกกกก
7.ผมว่าผมใช้ปืนถูกกฏหมายนะฮะ | Random 3 Weapons
Lostlife : Overlay + Freeze + Matrix + Stun
Passive : Can Revive all time

Download ลดขนาดไฟล์ลง
https://www.dropbox.com/s/1lpzrj9yi5emarw/gtx%20toxic%20lord.rar?dl=0

2.Amatsu-Mikaboshi

Model 1
![image](https://user-images.githubusercontent.com/51502238/81420536-4d787900-917a-11ea-9b46-bb7ae04f15da.png)

Model lostlife Fake Uber
![image](https://user-images.githubusercontent.com/51502238/81420688-81539e80-917a-11ea-9fc7-1dcfe3399106.png)

Ability : Super Jump And Weigh-down
Lives : 2
Rage : Nightmare + Invisible + Quick Fix + Sentry stun
Lostlife : Stun + Uber + Change Model and Weapon + Matrix + Spawn Alien Beam + Outline + Get teleport points 15
Passive : Can Revive all time +  Dark fog 

Download
https://www.dropbox.com/s/qjifksodh9zqb4t/corrupted%20jss.rar?dl=0

3.Cataclysm Slaughter

Model
![image](https://user-images.githubusercontent.com/51502238/81421421-ab599080-917b-11ea-81e1-90aa0dfc6180.png)

Ability : Super Jump And Weigh-down
Lives : 2
Lunge Press R to use cost 0 rage Colddown 20 seconds.
Rage Press E  : Stun +  Sentry stun + Gain Air Strike + Speed moving
Rage Press M3 : Guitar Hero
Lostlife : Change  Weapon + Hell Fire + Quick Fix all life + Gain Crits
Passive : Can Revive all time

Download
https://www.dropbox.com/s/la8b9vpns4a2uaw/overlord%20wingvoid.rar?dl=0

4.Corrupted War Machine

Model
![image](https://user-images.githubusercontent.com/51502238/81422103-b95be100-917c-11ea-9b7c-272c526bc2ed.png)

Ability : Super Jump And Weigh-down
Lives : 2
Super Slan Press R to use cost 50 rage Colddown 20 seconds.
Dot Laser Beam : Coat 60 Rage
Rage Press E  : Quick Fix + Random 2 weapons + Outline 
Lostlife : Freeze Stun + Red fog + Gain Loose cannon + Gain Crits + Gain Resistance Power up + Change Theme + Uber
Passive : Can Revive all time

Download
https://www.dropbox.com/s/99bnmmzne0vyoy8/corrupted%20war%20machine%20re.rar?dl=0

5.God of Intergalactic

Model
![image](https://user-images.githubusercontent.com/51502238/81423034-0ee4bd80-917e-11ea-933f-c6a687f3f2f5.png)

Ability : Super Jump And Weigh-down
Lives : 2
Rage Press E  : Super Stun + Chainlightning + Smites + Fog + Invisible + Spawn Alien Beam + Sentry stun
Lostlife : Uber + Matrix + Outline + Spawn Alien Beam
Passive : Can Revive all time

Download
https://www.dropbox.com/s/a7hvyufo7t5crgs/God%20of%20Intergalactic.rar?dl=0

6.Edgelord Ultima

Model
![image](https://user-images.githubusercontent.com/51502238/81423668-f88b3180-917e-11ea-9c1f-2836b611a3c6.png)

Ability : Teleport And Weigh-down
Lives : 2
Rage Press E  : Stun + Gain Ambassador
Lostlife : Matrix

Download
https://www.dropbox.com/s/hnfo86qephw1w1k/edgelord%20newest.rar?dl=0

7.Mad Machine Slaughter

Model
![image](https://user-images.githubusercontent.com/51502238/81424070-8d8e2a80-917f-11ea-9532-5dbfb7de3243.png)

Ability : Teleport And Weigh-down
Rage Press E  : Gain Liberty launcher + Sentry stun + Haste Power up + Gain Crits
Passive : Quick Fix all time

Download
https://www.dropbox.com/s/qfe8s3smbgetidd/mad%20machine.rar?dl=0

8.Dr.Fear

Model
![image](https://user-images.githubusercontent.com/51502238/81424499-43f20f80-9180-11ea-8a78-1de863585ef6.png)

Ability : Super jump And Weigh-down
Rage Press E  : Stun + overlay + speed moving
Passive : Dark fog

Download
https://www.dropbox.com/s/u0pzw02wpsiq1kh/dr.fear.rar?dl=0

9.Chief Concheror Soldier Bot

Model
![image](https://user-images.githubusercontent.com/51502238/81424725-97645d80-9180-11ea-9021-3a5a6ee78845.png)

Ability : Teleport And Weigh-down
Dot Teleport Press M3
Rage Press E  : Stun + Buff + Change model
Passive : Giant Model

Download
https://www.dropbox.com/s/3r3eexe22zef2af/shogun_soldierbot.rar?dl=0

10.Frenzied Spy

Model
![image](https://user-images.githubusercontent.com/51502238/81425369-a992cb80-9181-11ea-8081-e0cc76ed7180.png)

Ability : Super Jump And Weigh-down
Rage Press E  : Buff + Gain Big killer + Speed moving

Download
https://www.dropbox.com/s/q9dp6r2zped6xze/frenziedspy.rar?dl=0

11.Hentai Woody

Model
![image](https://user-images.githubusercontent.com/51502238/81425643-35a4f300-9182-11ea-91b2-71e952f0a69d.png)

Ability : Teleport And Weigh-down
Rage Press E  : Stun + Dark fog + Gain Crits + Uber

Download
https://www.dropbox.com/s/rx46w53yp1uycbf/hentai%20woody.rar?dl=0

12.Duke Nukem

Model
![image](https://user-images.githubusercontent.com/51502238/81425792-70a72680-9182-11ea-8ca6-d4f4393e153d.png)

Ability : Super Jump And Weigh-down
Rage Press E  : Stun + Gain Shotgun + Buff

Download
https://www.dropbox.com/s/f64eubhxnl3jj3j/duke%20nukem.rar?dl=0

Thank you
![image](https://user-images.githubusercontent.com/51502238/81426080-e0b5ac80-9182-11ea-902e-0544df0ddaf7.png)

**Comment by Sun9z** [comment]
Sun9z original

**Comment by Hidden-1** [comment]
Amatsu-Mikaboshi swipez wannabe

**Comment by Dablikeneko** [comment]
You know? Amatsu-Mikaboshi is My oc corrupted version

**Comment by Hidden-1** [comment]
still. swipez wannabe

**Comment by MrTheBank** [comment]
GitHub is not a place to discuss about shit, use discord instend

**Comment by MrTheBank** [comment]
GTX Toxic Lord ไฟล์ขนาดใหญ่เกินไป
God of Intergalactic, Hentai Woody ลิงค์ซ้ำ

**Comment by RedTerminal1912** [comment]
แก้ ลิงค์ซ้ำละครับ ส่วนเรื่อง GTX ผมจะไปลดขนาดลงแล้วส่งมาให้ใหม่คับ

**Comment by RedTerminal1912** [comment]
okay ฮะลดมันลงแล้วครับ ต้องการให้แก้อะไรก็ comment มาได้ครับ

**Comment by MrTheBank** [comment]
Corrupted War Machine ไฟล์ intromusic.mp3 หาย

**Comment by MrTheBank** [comment]
added all of bosses except GTX Toxic Lord (under-review).

**Comment by RedTerminal1912** [comment]
ยัดเพิ่มละคับ
https://www.dropbox.com/s/qeafb36gzonofux/corrupted%20war%20machine%20re.rar?dl=0
