### ISSUE TITLE
Nerf Pack 4 for perfact and balnce

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#66]
Nerf Boss And Nerf GTX File
File GTX and File cfg nerf in 1 download

https://www.dropbox.com/s/4d22me9y7gjfnvm/nerf%201.rar?dl=0

**Comment by MrTheBank** [comment]
removed old cfg and added new cfg

**Comment by Dablikeneko** [comment]
Low แล้วละครับ ถ้ามันมากเกินไปก็จะแค่เหลือเพลงจี้หอยเพลงแล้วครับ
https://www.dropbox.com/s/w9x96v885sd13fd/gtx%20toxic%20lord%20super%20nerf.rar?dl=0

**Comment by RedTerminal1912** [comment]
แก้ตัวนึงคับ
