### ISSUE TITLE
Boss i make Not ddos now(and that not shin)

### ISSUE THREAD

**Issue by raykoshima** [MrTheBank/Maxnus-Network#69]
Boss name Not Kenzo
Abilities: Superjump (Hold right click and look up) & Weigh-down (Hold CTRL and look down)
Rage: rage fire and chainlightning
Have 3 lifes
Have revive markers
video https://www.youtube.com/watch?v=fbSerFS42yg
link https://www.dropbox.com/s/hehoi0yaqyj0z3o/YothatnotKenzo.rar?dl=0
picture
![image](https://cdn.discordapp.com/attachments/589743954162089994/708964866274361434/BEF88D5D0A99A5844DC9FB0EEC663864B3DB332A.png)
thanks.

**Comment by Sun9z** [comment]
wtf i love this boss!!

**Comment by MrTheBank** [comment]
GitHub is not a place to discuss about shit, use discord instend.

**Comment by Sun9z** [comment]
sad moment
