### ISSUE TITLE
DUO Koishi has bug from Neko T!me

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#7]
Dead ringer just remove and add normal cloak
Abilities : She has no superjump fix to teleport pls
Make like new Solo Koishi pls มันเล่นยากมาก
Pls ask Nameless or pu shitcake to fix it
If she has fix.im thanks you :D 
Satori ไม่มีปัญหา

**Comment by MrTheBank** [comment]
แค่คู่หู Koishi ใช่ไหมครับ ไม่ใช่ตัวเดี่ยวใช่ไหมครับ

**Comment by RedTerminal1912** [comment]
yes only Koishi

**Comment by MrTheBank** [comment]
แก้ไขแล้วโดย Nameless
