### ISSUE TITLE
NERF GTX Toxic Lord File

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#71]
File sound 88 sounds

![image](https://user-images.githubusercontent.com/51502238/81530205-9b63cb80-938a-11ea-9df9-608d5655751f.png)

Download
https://www.dropbox.com/s/3oztmm5c8cp87v3/gtx%20toxic%20lord%20nerf%20file%20sound.rar?dl=0

**Comment by MrTheBank** [comment]
#79
