### ISSUE TITLE
MaKaValz's Revive Bosses Add (Also another nerfs)

### ISSUE THREAD

**Issue by PuShitcake** [MrTheBank/Maxnus-Network#74]
> _Old bosses' link expired, they aren't problem for us. We will bring them back._

So first, that I want to introduce is new model for him (except Tough Guy his uber is very good). I fixed hat style for NRC (before it not for soldier class, so now it's soldier). Also NRC's and Tough Guy's sounds too, change to use original sounds in TF2 instead of download (They are same sounds, why not), well let's look foward to boss information.

### 1.) No Random Crits V2

![nrc-v2](https://user-images.githubusercontent.com/63900170/81908226-2646ff00-95f3-11ea-87f4-e910042c9497.png)

His Abilities are Super Jump and Weigh-down
On lose life he will Uber and does Random Teleport
On Rage he will gain SUPER ROCKET LAUCNHER + Warning Overlay + Stun Players and Sentry (His rage sounds is map wide)

He is OP, so RED team has revive markers for them, and also he has low HP, high rage damage. He has plugins. They are already in his files.

### 2.) Tough Guy

![tough-guy-png](https://user-images.githubusercontent.com/63900170/81909226-7a061800-95f4-11ea-9ca2-0281a74aa57c.png)

His Abilities are Super Jump and Weigh-down
On lose life he will Uber + Matrix and Gain his SUPER SCATTERGUN
On Rage he will turn himself Invisible + Dodge every damage for 5 seconds when after that he has every -50% damage from everything (but fire is -80% because of Invisible). Also he has low gravity for 8 seconds and change his melee to faster firing speed but lower damage than main melee.

His melee deals high damage but has slow firing speed, he also has low HP too and normal rage damage. You can see the rage is not same like original because of original rage is very useless (defense buff and haste powerup with Invisible will show himself), so I decided to change his rage to not have defense buff but change to another plugin and use change weapon on rage with put defense attiributes of protection in it.

_**Download link:**_
MediaFire: https://www.mediafire.com/file/09saoohir3hikxn/Lord_Homicide%27s_Legends_%28Another_Nerfs%29.zip/file

**Comment by MrTheBank** [comment]
removed old cfg and added nerf one
