### ISSUE TITLE
-----SUGGEST MAP-----

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#76]
### **vsh_grid_walls_reworked_v1a**
![image](https://user-images.githubusercontent.com/63923202/82116361-71981380-9793-11ea-9f31-f6b5f97fe517.png)
### **vsh_casbah**
![image](https://user-images.githubusercontent.com/63923202/82116381-9b513a80-9793-11ea-8b0a-271d4bd807d4.png)
### **vsh_defroot_keep_2020 (replace old degrootkeep)**
![image](https://user-images.githubusercontent.com/63923202/82116411-d2275080-9793-11ea-8111-6ad133bf1345.png)
### **vsh_arcticbase_b3**
![image](https://user-images.githubusercontent.com/63923202/82116449-292d2580-9794-11ea-8d45-f3faac12ad9a.png)
### **vsh_skytower_b3**
![image](https://user-images.githubusercontent.com/63923202/82116465-419d4000-9794-11ea-839c-a468651d0a7c.png)
### **vsh_valvewater_b4**
![image](https://user-images.githubusercontent.com/63923202/82116490-6a253a00-9794-11ea-81cb-db3f18dc701d.png)
### **vsh_remains_of_king_b1**
![image](https://user-images.githubusercontent.com/63923202/82116513-980a7e80-9794-11ea-814f-dcf1c56a323d.png)
### **manncogym**
![image](https://user-images.githubusercontent.com/63923202/82116531-be301e80-9794-11ea-838c-eb6ed1b2404d.png)
### **vsh_north_mountain**
![image](https://user-images.githubusercontent.com/63923202/82116558-ed469000-9794-11ea-9040-dfc894052524.png)
### **vsh_secret_base_b2**
![image](https://user-images.githubusercontent.com/63923202/82116577-0e0ee580-9795-11ea-936e-f4be7fe933f0.png)
### **vsh_Top_arena_v1**
![image](https://user-images.githubusercontent.com/63923202/82116596-2da60e00-9795-11ea-831c-07678825dc05.png)
### **vsh_cactustemple_v1**
![image](https://user-images.githubusercontent.com/63923202/82116671-b1f89100-9795-11ea-9896-f6d421e30fb0.png)
### **vsh_shipment_v1**
![image](https://user-images.githubusercontent.com/63923202/82116742-19164580-9796-11ea-93d4-136194cd594f.png)
### **vsh_tower_of_peril_redux_v6**
![image](https://user-images.githubusercontent.com/63923202/82117090-1d436280-9798-11ea-9347-074a79d5bf90.png)

### **and I suggest to remove these map**
vsh_partyisland_v7
reason : hard to play as hale and player
vsh_helms_deep_v1
reason : tower spot can go down and sniper will use this to spot

แถม BZIP2 ใน dowload

**Comment by MrTheBank** [comment]
done
