### ISSUE TITLE
Add Boss and Plugins / Nerf and Buff

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#79]
Add Boss List

--------------------------------------------------------------------------------------------------------------

1.GT Sexy Lord
Big gay King engineer Class like Pu shitcake

![2](https://user-images.githubusercontent.com/51502238/82526837-2b5dfe00-9b5f-11ea-8e17-fa4de16ab748.png)

About Abilities : 
Mobility : Super Jump and Weigh-down
Lifes : 2
AMS Rage : 
-Rage Overlay สุด X Sexy โดโยตี้เต้นอยู่หลังรถ
-Rage Nightnare เปลี่ยนทุกคนให้เป็น เด็กในบรา gay
-Rage Speed Moving Boss ต้องการวิ่งไปที่ด้านหลังคนอย่างรวดเร็ว
-Rage TFcond1 ทำให้คนอื่นยืนนิ่งๆ แล้ว Boss ก็ตบตูดไป
-Rage Stealing ขโมยทุกอย่าง ยัน กกน
-Rage TFcond2 Super Powerful gay power
Lostlife Abilities : Matrix + Stun + Uber
Passives : 
Can Revive 
Intro Overlay
Kill Overlay

2.Super War Machine 
Frist Version Of Corrupted War Machine

![image](https://user-images.githubusercontent.com/51502238/82526100-4891cd00-9b5d-11ea-8b13-5e373ddb2c3a.png)

About Abilities : 
Mobility : Super Jump and Weigh-down
Lifes : 1
Rage : Sentry stun + Short stun + Uber + Berserk + Outline + Fog + Gain Buff + Shot 20 Rockets
Passives : Can Revive 

3.Kaiser wilhelm Medic
Not oc boss

![image](https://user-images.githubusercontent.com/51502238/82526160-7d9e1f80-9b5d-11ea-915a-1eaaa1d29bf7.png)

About Abilities : 
Mobility : Super Jump and Weigh-down
Lifes : 1
Rage : Stun + Quick-fix effect + Defense Buff + Regen Buff + Gain Bazaar Bargain

4.Biohazard#15
Meme Boss

![image](https://user-images.githubusercontent.com/51502238/82526348-fdc48500-9b5d-11ea-9e1a-5207a8b2f5cd.png)

About Abilities : 
Mobility : Teleport and Weigh-down
Lifes : 1
Rage : Stun + Stun sentry + Plague powerup + Gain 2 teleport points
Passives : Dark Fog All time

--------------------------------------------------------------------------------------------------------------

Nerf And Add Plugins

--------------------------------------------------------------------------------------------------------------

แก้ตัว Boss GTX Toxic Lord ลดขนาด file sound
Nerf Sound MLG Demoman แก้ sound ใหม่ไม่ให้ดัง earrape
Nerf Cataclysm Slaughter
Nerf Megumin 

--------------------------------------------------------------------------------------------------------------

เพิ่ม Intro Overlay ให้พี่โต (Ricardo)
Buff Billy The Doll Limit การชุบ ชุบได้แค่ 3 รอบ
เพิ่ม Plugins จะอยู่ภายใน File Boss : GT Sexy Lord , Super War Machine , Billy the Doll

Download Pack
https://www.dropbox.com/s/8zw6zn9ggr9el9y/pack.rar?dl=0

Thank You For Read My Suggest Stuffs

![gay](https://user-images.githubusercontent.com/51502238/82526784-08334e80-9b5f-11ea-8e75-f2b692b9b5c2.png)

--------------------------------------------------------------------------------------------------------------

**Comment by MrTheBank** [comment]
nerf gt sexy lord's files a bit pls

**Comment by RedTerminal1912** [comment]
หายไปเยอะ แต่ก็ยังคงความ sexy ไว้อยู่

https://www.dropbox.com/s/sgbhzut83f1db3q/GT%20Sexy%20lord.rar?dl=0
