### ISSUE TITLE
จาก Neko T!me

### ISSUE THREAD

**Issue by RedTerminal1912** [MrTheBank/Maxnus-Network#8]
Epic scout
https://forums.alliedmods.net/showpost.php?p=2324892?p=2324892
ให้แอดลองพิจารณาก่อน add ละกัน https://www.youtube.com/watch?v=6AdfdKUjhUc

**Comment by MrTheBank** [comment]
**ผ่าน** ครับ บอสจะถูกแอดในแพ็คที่ 5
