### ISSUE TITLE
Another True Admin?

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#87]
**True Time Ruler**

![truetime_edit](https://user-images.githubusercontent.com/34367924/82907992-89d91100-9f91-11ea-916b-d1f165cbaed7.png)
![lowqualitytrue](https://user-images.githubusercontent.com/34367924/82916776-b0507980-9f9c-11ea-9c89-4c90e2e5ce94.png)

Class: Sniper
Health: (((520+n)*n)^1.03)/1.6
Max Speed: 380
Disable boss being choose in first round of map
He can random crits and he get 2 lives!

>**Abilities&Passive**

Super Jump,Weight Down, Revive Marker(2min 4 revives),immune soft stuns,Free rage (4 players left or below)
Dot Swap Weapon
Assault mode: Deal alot of damage but he taken more damage too
Protection mode:Deal abit low damage and he take very low damage (can be use when get 25% rage or more drain 1% per sec)

>**RAGE**

De level sentry (Delay 1s) 
Destruction building range 1200 (can be save by pickup) 
No knock back 
Increase host time scale to 1.3 for 6sec 
Summon death players

>**LOSE LIFE**

Bonk Stun everyone in map
Instant kill all players in range 500
Random all randomize peoples various charge meters
Freeze everyone include boss
Sentry stun

>**PLUGINS USED**

ff2_dynamic_defaults
ff2_otokiru_wc3
ffbat_publicpack
ff2_sarysamods6
drain_over_time
public_dots
ff2_sarysamods
ff2_sarysamods3
ff2_tfcond
ff2_sarysapub3
ff2_salmon
ff2_darthmule_stripped (Include in file)
ff2_tfcond2
shadow93_abilities
mann_up_abilities

DOWNLOAD: [fc zell kub](https://www.dropbox.com/s/p0zsftdcb5uun4r/ttr%20re.zip?dl=0)

![smug](https://user-images.githubusercontent.com/34367924/82916322-1b4d8080-9f9c-11ea-8e84-1b89aa3dd78d.png)

**Comment by PoomyInsurgency** [comment]
It​ Nice

**Comment by Reversesniper** [comment]
Updated boss ability and link

**Comment by MrTheBank** [comment]
Added to Pack 5
