### ISSUE TITLE
[MAP] My Map - Spothouse VSH

### ISSUE THREAD

**Issue by gongpha** [MrTheBank/Maxnus-Network#89]
My unfinished map. But today, It's now success.
Why the heck map name is SpotHOUSE ???

### Features
- Like another VSH Maps.
- Catapult (Brickyard)
- Basic optimization (Areaportal, Visleaf Cutting)
- HDR
### Notice
- This map had own custom sounds / textures.
- If you see the water like a checkerboard, just exit the game or re-building cubemaps.
- This map contains an easter egg. If you are honest, Just find it yourself. Don't decompile this.
- Ignore `Attempted to create unknown entity type kongpharealtree!` and `Can't init kongpharealtree` in console
- No Sun9z Easter Egg Here
- PhasaThai YooNaiKan ?

### Detail (Skip this, You are an user)
```
Total triangle count: 17727

names       Objects/Maxobjs  Memory / Maxmem  Fullness 
------------       ---------------  ---------------  -------- 
models                  31/1024         1488/49152    ( 3.0%) 
brushes               1190/8192        14280/98304    (14.5%) 
brushsides            7796/65536       62368/524288   (11.9%) 
planes                3658/65536       73160/1310720  ( 5.6%) 
vertexes             10184/65536      122208/786432   (15.5%) 
nodes                 2544/65536       81408/2097152  ( 3.9%) 
texinfos              1390/12288      100080/884736   (11.3%) 
texdata                157/2048         5024/65536    ( 7.7%) 
dispinfos              113/0           19888/0        ( 0.0%) 
disp_verts            7865/0          157300/0        ( 0.0%) 
disp_tris            12256/0           24512/0        ( 0.0%) 
disp_lmsamples      911944/0          911944/0        ( 0.0%) 
faces                 6311/65536      353416/3670016  ( 9.6%) 
hdr faces             6311/65536      353416/3670016  ( 9.6%) 
origfaces             3294/65536      184464/3670016  ( 5.0%) 
leaves                2576/65536       82432/2097152  ( 3.9%) 
leaffaces             8406/65536       16812/131072   (12.8%) 
leafbrushes           3656/65536        7312/131072   ( 5.6%) 
areas                   14/256           112/2048     ( 5.5%) 
surfedges            43502/512000     174008/2048000  ( 8.5%) 
edges                26889/256000     107556/1024000  (10.5%) 
LDR worldlights         58/8192         5104/720896   ( 0.7%) 
HDR worldlights         58/8192         5104/720896   ( 0.7%) 
leafwaterdata            8/32768          96/393216   ( 0.0%) 
waterstrips            782/32768        7820/327680   ( 2.4%) 
waterverts               0/65536           0/786432   ( 0.0%) 
waterindices         13473/65536       26946/131072   (20.6%) 
cubemapsamples          48/1024          768/16384    ( 4.7%) 
overlays                62/512         21824/180224   (12.1%) 
LDR lightdata         [variable]    14637336/0        ( 0.0%) 
HDR lightdata         [variable]    14637336/0        ( 0.0%) 
visdata               [variable]      281149/16777216 ( 1.7%) 
entdata               [variable]       59022/393216   (15.0%) 
LDR ambient table     2576/65536       10304/262144   ( 3.9%) 
HDR ambient table     2576/65536       10304/262144   ( 3.9%) 
LDR leaf ambient     15057/65536      421596/1835008  (23.0%) 
HDR leaf ambient     15057/65536      421596/1835008  (23.0%) 
occluders                0/0               0/0        ( 0.0%) 
occluder polygons        0/0               0/0        ( 0.0%) 
occluder vert ind        0/0               0/0        ( 0.0%) 
detail props          [variable]           1/1927532  ( 0.0%) 
dtl prp lght          [variable]           1/4        (25.0%) 
HDR dtl prp lght      [variable]           1/4        (25.0%) 
static props          [variable]           1/68026    ( 0.0%) 
pakfile               [variable]     5202360/0        ( 0.0%) 
physics               [variable]      417022/4194304  ( 9.9%) 
physics terrain       [variable]       33557/1048576  ( 3.2%) 

```

![ภาพ](https://cdn.discordapp.com/attachments/269630139258634242/716273569654374540/unknown.png)
![ภาพ](https://cdn.discordapp.com/attachments/269630139258634242/716273641020457050/unknown.png)
![ภาพ](https://cdn.discordapp.com/attachments/269630139258634242/716273761808285716/unknown.png)
![ภาพ](https://cdn.discordapp.com/attachments/269630139258634242/716273827222650910/unknown.png)
![ภาพ](https://cdn.discordapp.com/attachments/269630139258634242/716274698715004928/unknown.png)
![ภาพ](https://cdn.discordapp.com/attachments/269630139258634242/716274778285277205/unknown.png)
(These are 1080p and HDR)

### Don't Forget
![ภาพสุดยอด](https://cdn.discordapp.com/attachments/269630139258634242/716274858169991179/unknown.png)

### File ?
[DOWNLOAD HERE via MEGA (No Decryption Key)](https://mega.nz/file/ANcXhAgI)

### Key ?
**THE KEY IS IN a DISCORD group**

### HOW to install ?

1. Download it from above LINK (ALSO get a key too)
2. MEGASync if you can. Suck A Speedmouse
3. Absolutely, You will get a RAR File. IF you get a ZIP File. Please get out of the window.
4. Download AN Extractor Program (WinRAR ?) if you aren't often mention to it.
5. Open That RAR
6. A RAR contains one file. If you see multiple files. Please get out of the country.
7. Open your TF2 Map Directory (`tf/maps` or `tf/download/maps`. GOOGLE it if you don't know)
8. Drg&Drp
9. Make sure you aren't install in `hl2` folder.
10. Profit ?

### _IF YOU WANT A VMF FILE, CONTACT ME FOR A FILE. DON'T USE A SHITTY DECOMPILER_

(This map will get upload on GameBanana too. If I can)

**Comment by gongpha** [comment]
~~[KUNCHAE THEE CHA KHAI RAHAD FILE](https://discordapp.com/channels/284885278060052482/284885278060052482/716288408116265000)~~ 
Key is deleted. Lucky Elephant.

**Comment by MrTheBank** [comment]
Approved and changed default map (when server is start or restart) to vsh_spothouse.

**Comment by gongpha** [comment]
TODO :
- [x] Some props are non-solid. Players can walking through it
- [x] Reduce some props
- [x] Better VVIS Optimization
- [x] Areaportal Shit
- [x] New Building
- [x] Overlay Missing

**Comment by gongpha** [comment]
New Version : [DOWNLOAD HERE via MEGA (No Decryption Key)](https://mega.nz/file/ZJFTgaBC)
### Changes
As above

**Comment by gongpha** [comment]
NEW : https://mega.nz/file/cAcRVKiK

**Comment by gongpha** [comment]
[New Link](https://bit.ly/3cj0CKb)

**Comment by gongpha** [comment]
New Update (MQ1) :
- 2 new catapults
- 2 new ladders (for trickstab gods)
- Fix some Overlays are missing
- New Ammo box place
- Better VVIS Optimization (Do nothing)
- Rick May Memorial Statue (After 1 June, Now invisible.)

https://bit.ly/36QbBK7

**Comment by gongpha** [comment]
New Update (MQ2)

- 15 new ladders (why did i do this)
- Fixed glitchy truck (Now, it parks inside the building)
- MODIFIED EASTER EGG
- Add more props

https://mega.nz/file/YJMCTKKI

**Comment by gongpha** [comment]
TODO in MQ3 :

- [x] ~~Remove all ladders~~ (Polygons aren't ladders)
- [x] Reduce Props


- [x] Fix Overlays
- [x] More portable ways
- [x] Improve more HINT for VVIS
- [x] Recompile a map

**Comment by gongpha** [comment]
If owner doesn't mind, Please open this issue when i posted TODO.

**Comment by gongpha** [comment]
New Update on MQ3 :

- More VVIS Optimization
- Reduced Props for more performance
- Added more portable ways
- Fixed overlays
- Updated Easter Eggs (Old was obsoleted)

https://mega.nz/file/VJkwSQCa

**Comment by gongpha** [comment]
TODO in MQ4 (Merged by MQ5) :

- [x] Areaportal
- [x] Compiling

**Comment by gongpha** [comment]
New Update on MQ4 :
- Fixed Areaportal Leaks
- Removed Prop that causes problem

https://kongfapoint.com/private/2563/bsp/vsh_spothouse/vsh_spothouse_maxnus_mq4.rar

**Comment by gongpha** [comment]
WebSite Phom Kak Mak

**Comment by gongpha** [comment]
TODO in MQ5 :
- [x] Replace NODRAW with TRIGGER at BRUSH 84723
- [x] Insert NOBUILD
- [x] More easter egg place
- [x] Remove shitty metadata on invisible entity
- [x] Compiling Again ???

**Comment by gongpha** [comment]
ถ้าถึง MQ6
ผมจะเริ่มสร้าง Map ใหม่ละ

**Comment by gongpha** [comment]
Tried fix instantly in BSP File.

Link soon

**Comment by gongpha** [comment]
Not working

Rollback.

**Comment by gongpha** [comment]
New Update on MQ5 :
- Moved Prop to prevent a glitch
- More Easter Egg

https://kongfapoint.com/private/2563/bsp/vsh_spothouse/vsh_spothouse_maxnus_mq5.rar
