### ISSUE TITLE
จาก kaito #2

### ISSUE THREAD

**Issue by Reversesniper** [MrTheBank/Maxnus-Network#9]
https://cdn.discordapp.com/attachments/575198724083548162/591872835941695489/unknown-2.png
ภาพ model
Replace: Crossz scout (own of oc want change)
P.S credtis to model koishi to juegospablo
ReaperBoyZ
Class: scout
health formula (((620+n)*n)^1.04)/2
max speed: 380
2 lives
Ability: 
superjump with weightdown
Lunge cost 0 rage cooldown 15s
Passive: revive maker 30s
Rage: fog+outline+berserk+no knock back all effect duration 10s
On lost life:stun player for 4s + stun building for 8s + uber for 6s + gain a scattergun for 30s
summon a koishi with 600 hp.
Download link
https://www.dropbox.com/s/nok9i3a9p1wdsyg/ReaperboyZ.zip?dl=0

สามารถบอกให้ nerf ได้นะคับ

**Comment by MrTheBank** [comment]
เสื้อบัค ไม่มีสกิน

**Comment by Reversesniper** [comment]
เดี่ยวแก้คับ

**Comment by MrTheBank** [comment]
ท่านเรียงเลข download ผิด.... เลยทำให้ไฟล์โหลดไม่ครบ ตอนนี้ผมแก้ให้แล้วนะครับ **ผ่าน** บอสจะถูกแอดในแพ็คที่ 3 และลบ CrossZ Scout
