### ISSUE TITLE
FIX BUFF NERF AND BOSS SUGGEST FROM NEKO T!ME

### ISSUE THREAD

**Issue by ZELLLLEZ** [MrTheBank/Maxnus-Network#92]
**Volcano : Fix error
NotKenzo : Fix Download
Sirenhead : Fix intro overlay no animation
Waails MK2 : Fix Material added new animation can taunt like normal scout and not A pose when Swim
Monika : Fix nightmare error model
Zelan : Fix rage**

BUFF & NERF
Beatrice,NUKED,Dark realms,wizardspy,field doctor

**_DOWNLOAD FIX BUFF AND NERF : https://drive.google.com/file/d/1b11NPV8Hn0aIjezS03wK2Eo727XOLLaf/view?usp=sharing_**

**SUGGEST BOSS**
**_Corrupted Woody_**
![image](https://user-images.githubusercontent.com/63923202/83937217-1b981800-a7f5-11ea-95d6-e3cb7487493e.png)
Abilities
Super Jump (Let Go Under 100 Percent)
Teleport (Hold Until 100 Percent).
RAGE
Gains Uber
Overlays Peoples Screens
Stun (+ Sentry Stun)
Crits.
Life Loss
Teleports TO a Random Player
Passive
Fog Effect.

**_SammyClassicsonicFan_**
![image](https://user-images.githubusercontent.com/63923202/83937238-5306c480-a7f5-11ea-81c2-4a303db37bd4.png)
![image](https://user-images.githubusercontent.com/63923202/83937395-4f277200-a7f6-11ea-85a2-22c13241e7ff.png)

Super Jump
Weighdown
RAGE: Gains Grenade Launcher + Mini Crits + Spawns Sonic The Hedgehog
LIVES: You Have 2 Lives, When You Lose One, You Gain Faster Speed, Faster Melee Swing And Slow Mo (NOT MATRIX ATTACK)

**_SuperproDemoman_**
![image](https://user-images.githubusercontent.com/63923202/83937300-9f520480-a7f5-11ea-926e-baddef9c8d19.png)
Stats
Class: Demoman
Health Formula: (((760+n)*n)^1.04)
Lives: 1
Movement Speed: 350 hu/s
Total damage needed to activate rage: 3000
Weapon: Bottle(Nothing special for his startup melee, but hard to explain all 7 different melees he switches so I won't go deep on that)

Abilities
Mobility: Lunge(Has no damage when hitting an enemy, but destroys buildings instantly, and has 4 seconds of cooldown), Weighdown
Other Abilities: Switches 1 of 7 different melees every time he kills someone. Each melee has different stats that was featured in the video.
Rage: Stun all sentries for 10 seconds + Gets Uber, Haste Powerup, Minicrit, and Knockback Resistance(All 10 seconds) + Gets 450 hu/s Speed Boost(10 sec) + Gets 1 of 3 different grenade launcher for 10 seconds. Each grenade launcher has rapid fire rate and reload speed, but low damage.

**_Superminecraftkid_**
![image](https://user-images.githubusercontent.com/63923202/83937294-94976f80-a7f5-11ea-8e9d-abfd5e964ed7.png)
 Weapon: Frying Pan
Rage: Summon Chica's with "meat" + Stun
Lifes: 2
Life-loss: 10-shot bad aim Revolver-pistol + Slowdown time
Abilitys: Brave jump, weighdown, DOT.
Drain over Time (DOT) Info: Hit R when you have 50% rage or more to gain super-speed and run like Sanic! + Crits.

**_Download SUGGEST :  https://drive.google.com/file/d/1btbjVBcVJQY8Co3iIf5NNgURH_FTAu5h/view?usp=sharing_**

**Comment by MrTheBank** [comment]
Replace fix and buff files to server

**Comment by ZELLLLEZ** [comment]
Update 2 cfg
Zelanthebetrayer[fix a pose,delete crit to red teams change weapon stats]
Dark realms[fix chain lighting change skill hud and description]

**Download : [fixagain.zip](https://github.com/MrTheBank/Maxnus-Freak-Fortress-2/files/4739668/fixagain.zip)**

Thank you.

**Comment by MrTheBank** [comment]
![20200622084720_1](https://user-images.githubusercontent.com/16158569/85241290-85efc000-b465-11ea-81f9-f6c98a6698ad.jpg)
![20200622084814_1](https://user-images.githubusercontent.com/16158569/85241295-87b98380-b465-11ea-8632-b1f32aede761.jpg)
SammyClassicSonicFan model error
![20200622085033_1](https://user-images.githubusercontent.com/16158569/85241322-9d2ead80-b465-11ea-8a37-226e2b19c53a.jpg)
Super Minecraft Kid model error เช่นกัน และ
ไฟล์เสียงหาย
![image](https://user-images.githubusercontent.com/16158569/85241365-c3ece400-b465-11ea-8824-ea82e3685a86.png)

ที่ผ่านและสามารถอัพเข้าเซิฟจะมีแค่ SuperproDemoman กับ Corrupted Woody

**Comment by MrTheBank** [comment]
สำหรับ SammyClassicSonicFan และ Super Minecraft Kid #110 

ส่วน SuperproDemoman กับ Corrupted Woody รออัพเข้าเซิฟเวอร์
