### ISSUE TITLE
Boss Add: Mega Solo Wave #6

### ISSUE THREAD

**Issue by PuShitcake** [MrTheBank/Maxnus-Network#95]
Here's he come the project that I lazy to do for year(s).

### **TAE EXZENFIRE**

![hfuhkqlvwbnm5yhkt4sghoqixcgsmdqi](https://user-images.githubusercontent.com/63900170/83960253-d33e3000-a8b0-11ea-970c-c8d9b3a2274d.jpg)

Rigged to Spy but it's Sniper in view model.

_WARNING: BOSS UNTEST_

Know bug:
- When hold weapon that get from rage, it will become civilian because of Spy rigged.
(Yes, and I won't fix except I will get another 3 keys, please donate I'm poor as frick right now.)

His abilities: Super Jump and Weigh-down
Special abilities: Overlay on start and kill and also his voice is special.
Rage: Overlay + Mini-Crits + Defense Buff + Random Weapon + Change enermies to Watermelon

**Download link:**
Mediafire: https://www.mediafire.com/file/8q075qd676w0ghq/%u0E40%u0E15%u0E40%u0E15%u0E49%u0E19%u0E31%u0E01%u0E27%u0E32%u0E07%u0E40%u0E1E%u0E25%u0E34%u0E07_%u0E01%u0E31%u0E1A_My_Mate_Nate_%u0E19%u0E31%u0E01%u0E27%u0E32%u0E07%u0E40%u0E2B%u0E23%u0E35%u0E22%u0E0D%u0E1A%u0E19%u0E23%u0E32%u0E07%u0E23%u0E16%u0E44%u0E1F.zip/file

**Comment by PuShitcake** [comment]
Change log:
- Update download link.

**Comment by MrTheBank** [comment]
Added to Pack 5
